### ISSUE TITLE
Aufnahme Initale Mitglieder

### ISSUE THREAD

**Issue by culmat** [BaselHack/Verein#1]
Neben den an der Gründungssitzung bereits aufgenommen Mitgliedern, haben folgende Personen im Vorfeld mitgearbeitet.

Sollen wir Sie alle aufnehmen, falls sie dies möchten und im laufenden Jahr beantragen?
Dann müssen wir nicht jeden einzeln bestätigen.

- Benjamin Rüde
- Brani Siarsky
- Goran Brodnik
- Jonas Jatsch
- Marina Morawietz
- Michel Pfirter
- Michael Börner
- Stefan Philippi

**Comment by culmat** [comment]
:white_check_mark:

**Comment by Brenzikofer** [comment]
Ich bin einverstanden - LG Thomas

**Comment by ghost** [comment]
:white_check_mark:

**Comment by culmat** [comment]
2/3 -> OK
