### ISSUE TITLE
Raum-Reservation HGK

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#10]
HGK
-> Marina

**Comment by mabrimo** [comment]
Who of you would be willing to take a look at the location in Dreispitz to check for technical requirements in the week from 24th-28th one day in the morning (the responsible Lady is only working part time)? Please comment and I will make a doodle to fix the date.

**Comment by andgart** [comment]
@mabrimo happy to help
@andgart - thanks! wann hättest du nächste Woche Vormittag gut Zeit?

**Comment by OliverFritsch** [comment]
@mabrimo: I'd like to join as well.

**Comment by teddybeaker** [comment]
Infos:
- Können Aussenbereich mitnutzen
- Empfang kostet evtl. weniger oder nichts
- technische Unterstützung kostet
- Freitag ab 19Uhr dürfen wir in die Räume
- offiziell darf nicht übernachtet werden
- Kühlschrank (gross) und Kaffeemaschine können wir nutzen
- Putzdienst kommt am Montag Morgen, bis dann muss alles abgebaut sein

Noch offen:
- brauchen wir Security?
- sind wir bei Catering gebunden? SV offizieller Caterer, aber evtl. anders weil Wochenende.
- können wir einen Lounge-Bereich einrichten? Evtl. bringen wir selber Sachen mit?

**Comment by culmat** [comment]
Zur Info. Habe mal eine Offerte für WLAN eingeholt: https://drive.google.com/drive/folders/0BwYmOJdMXmpiRk1fUEF2WnFBYkk  -> wäre super, wenn es ohne externen Provider klappt ;-)
