### ISSUE TITLE
find jury members

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#100]
- decide how many
- what are the tasks of a j member

**Comment by mayvi** [comment]
- Verschiedene Kompetenzen sollen in der Jury vertreten sein.
   - wenn wir diese nicht besetzen können, nehmen wir Jury Mitglieder aus unserem Verein
- Jury soll präsenter sein und ein paar Stunden am Event dabei sein.

**Comment by culmat** [comment]
Baloise: POZ ?

**Comment by culmat** [comment]
Vorschläge (TB)
Adrian Bult, Basler Kantonbank
Alain Bindels, Roche
Abhi Verma, Novartis
Andrew Warrington
Desiree Mettreaux, Creadi PAX
