### ISSUE TITLE
define evaluation criteria for hacks

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#101]
- for the jury

**Comment by mayvi** [comment]
Judging criteria of other hackathons:

[**Longmont hackathon**](http://longmonthackathon.com/judging-criteria/)
10% – user experience
30% – increment/innovation
30% – impact/potential/sustainability
30% – sharing resource/collaboration

[**Open dutch hackathon**](https://dutchopenhackathon.com/p/judging)
**Viability**
Has the project a realistic chance of being implemented by partners, is the idea scalable and applicable to more industries. Is it realistic to further develop the project? 
**Originality**
Is your project creative, new and innovative? Is it something we already know or is the idea disruptive?
**UX**
How is the design and user experience of your project? Is it easy to understand and use?
**Wow-effect**
Can you amaze the judges with new use-cases, big opportunities or surprises? How much did you achieve during the hackathon?

An other idea could be involving the community or judge in diffrent rounds (preselection, finals)

**Comment by mayvi** [comment]
- 2 Gewinner küren:
1. für die beste Idee
2. für die beste Umsetzung (Code u. technische Lösung) --> oder das technische Konzept zur Umsetzung

- Die Bewertung wird während einer Präsentation und einem Code Review / technischem Review gemacht

Ideen für Bewertung:
x % für Präsentation
x % für technische Umsetzung

**Comment by schmidchr** [comment]
see also documents, criteria from BaselHack2017 on our Google Drive (please keep password protected): https://drive.google.com/drive/folders/0B09yKrP7j_7IR1VSWUp0eEVwZ0U?usp=sharing

**Comment by schmidchr** [comment]
open source code (on github) -> requires time and knowledge from judges <br>
publicly accessible prototype, linked on project page -> BaselHack to provide server space

**Comment by mayvi** [comment]
I created an updated evulation criteria sheet in Google Drive incl. evaluation sheet (Event Folder 2018). The criteria are the same as last year. I have adapted the text a little.
