### ISSUE TITLE
Organize awards

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#102]

**Comment by sabinsc** [comment]
read this, please: http://metaodi.ch/posts/2014/01/stop-making-stupid-open-data-contests/

**Comment by mayvi** [comment]
- Konzept für Awards (Finanzierung)
  - Sponsoren für Awards kontaktieren
  - Awards selber mit Budget finanzieren?
- Wie viele Awards für die verschiedenen Ränge und/oder Disziplinen/Kategorien. --> Siehe Konzept zu Event

**Comment by mayvi** [comment]
Die Zentralen Informatikdienste des Kt. Basel-Stadt werden wieder Pro Innerstadt Gutscheine spenden. Der Betrag ist noch nicht bekannt.
