### ISSUE TITLE
Define target group

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#103]
... of the participants at the hack

-> should be discussed and ok for everybody

**Comment by mayvi** [comment]
Alle sind willkommen
- Wie binden wir die verschiedenen Zielgruppen ein, Mailing listen, ...

Folgende Gruppen wollen wir spezifisch anvisieren:
- Informatiker / Software Entwickler / Nerds  --> Dominik, Vivienne
- Entwickler Hardware / Ingenieur / IoT / Robotik --> Andres, Michel
- Business, Ideenbringer / Innovatoren / Business Developer, Business Angel --> Andres, Michel, Christoph, Vivienne
- Sozial/HR  --> Dominik, Michel
- Künstler / UX / Kreative / Grafiker / Musiker --> Christoph, Michel
- Umland (DE, FR) -> Ausbildungsinstitutionen
- Studenten/Lehrlinge --> Vivienne, IT-Scouts
