### ISSUE TITLE
Create and define a concept

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#104]
- do we have sponsored streams
-  ... topics
...

**Comment by mayvi** [comment]
Ideen:
- Games einbauen für Fun/Teambuilding --> Turnier mit Wertung (siehe Impact)
   - Höchste Score gibt einen Preis

Agenda:
- (Installation, Bilder aus dem letzten Event zeigen)
- Begrüssung
- Coaches stellen sich vor
- Jury stellt sich vor
- Sponsoren stellen sich vor
- Pitchen
- Teambuilding
---
- DJ oder eine Band
- technische Gadgets ausprobieren (FHNW)
- (konstante Gaming Möglichkeiten)
- (Red Carpet)
- Mittag- / Abendessen und Brunch
- Speedating für Jobchancen mit Sponsoren
- Warm up am Sonntag
---
- Präsentation
- Jurybewertung ( + Programm während Evaluation)

**Comment by culmat** [comment]
drehstühle für Jury

**Comment by culmat** [comment]
Klaus Fuchs von http://Rockstar.jobs  bietet an einen CV-Check-Booth zu machen
