### ISSUE TITLE
Organize data (providers)

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#105]

**Comment by andgart** [comment]
Happy to help in this issue!
(ideas: Stadt BS, integrate / support opendata.ch-Verein: their idea, give them a platform, ask them for help, etc., novartis etc.)

**Comment by schmidchr** [comment]
see comment by @sabinsc in issue #102 pointing to a [blog entry](http://metaodi.ch/posts/2014/01/stop-making-stupid-open-data-contests/), which questions the efficacy of hackathon competitions to promote Open Government Data (OGD)
