### ISSUE TITLE
Provide technical plattform for the hacks

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#107]
- define
- create handouts ....
- participant kit

**Comment by culmat** [comment]
maybe have a look at https://github.com/loleg/dribdat

**Comment by StanBarrows** [comment]
Thanks a lot! I'll have a look!

**Comment by culmat** [comment]
https://gitter.im/BaselHack/

**Comment by jjerlich** [comment]
We have all person data in the backend of the website to reach the people.
We can get feedback from groups / leaders through Mailchimp or through a GoogleForm
