### ISSUE TITLE
What is the impact for the participants?

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#108]
- fun
- what should they learn
...

**Comment by mayvi** [comment]
“BaselHack is more than a Hackathon – we connect people, take fun seriously and grow open innovation”

Ideen für Hackathon:
- Spiel (max. 1 Stunde) um Collaboration zu fördern: EscapeRoom, Postenlauf, Poker, Schach, 'Töggele', Play Station oder andere Spielconsole, Wii/Switch Game Punktestand fliesst in die Bewertung ein, Kinder in den hackathon einbeziehen --> Vivienne, Michel
- Coaches sollen sich vorstellen und sind über einen bestimmten Kanal erreichbar (Slack, Mail, Mobile)  --> tbd
- Künstlerischen Aspekt einbringen (Location, Deko, Technik etc.) --> tbd
- Event auf Location ausrichten (in HGK z. B. künstlerische, technische Installation/Anzeige) --> tbd
- Jury mehr in den Event einbeziehen (Vorstellen während des Hacks und ein paar Stunden Anwesenheit sollte Pflicht sein) --> Christoph
- Plattform für während dem Hack, auf welcher man sieht, was läuft. Man sich austauschen kann. (Ideen: Twitter Channel, Oleg) #107 --> Andres

--> Bspw. Playstation Game (1 Console mit 8 Smartphones als Controller) für eine Stunde Abwechslung
--> Microsoft, Sony und Nintendo als Sponsor anfragen

**Comment by schmidchr** [comment]
suggestion to edit the title of this issue:
What is the impact **for** the participants?
