### ISSUE TITLE
Retro BaselHack bei Smart Regio

### ISSUE THREAD

**Issue by JJatsch** [BaselHack/Verein#114]
Roadshow BaselHack bei GV Smart Regio. Ca. 18:30 Uhr am 19.03. im FluxDock. 
Ansprechperson: Elias Schäfer (elias.schaefer@fluxdock.io).
Ich habe Dietrich Rordorf (Ideengeber Clockchain) angeschrieben, ob er auch ein paar Worte sagen kann.
In der Präsentation fände ich diese Struktur toll:
BaselHack: Wer steckt dahinter und warum?
BaselHack 2017: Wie war's? Sicht Veranstalter und Teilnehmer
BaselHack 2018: Wie geht's weiter?

Das meiste gibt's ja glaub ich schon in irgendeiner Form.

Smart Regio haben angekündigt, dass sie uns gern weiter unterstützen wollen. Ich kann gern am 19. mitkommen, bin aber die ersten zwei Märzwochen in den Ferien, kann daher nicht mit vorbereiten.

**Comment by StanBarrows** [comment]
Gibt es hier Neuigkeiten? Wer präsentiert von den Projekten?

**Comment by jjerlich** [comment]
Roland Berger ist vom Gewinnerprojekt dabei.
@StanBarrows präsentiert eure Gruppe auch?

**Comment by StanBarrows** [comment]
@jjerlich Hallo Jutta, ich kann leider nicht an der Präsentation dabei sein. Kann aber gerne noch Infos zur Verfügung stellen. Liebe Grüsse Sebastian
