### ISSUE TITLE
Pre-Event organisieren

### ISSUE THREAD

**Issue by StanBarrows** [BaselHack/Verein#116]
Abklärungen bezüglich dem Pre-Event

**Comment by StanBarrows** [comment]
Sponsoring Event?

**Comment by StanBarrows** [comment]
Joint-Venture - >SwissMadeSoftware

**Comment by mayvi** [comment]
Pre Event als Plattform für Sponsoren oder Datenbringer um Idee vorzeitig zu pitchen oder einen Themenbereich zu prägen + Insights vom letzten Jahr + Vorbereitung für Hackthon bezüglich Teambuilding und wie wird am hack gearbeitet (Slack Channel, Github) + Agenda für BaselHack vorstellen + Pre Event soll als Brücke zum Hack dienen (Vorteil, wenn man am Pre Event kommt).

--> Konzept für Pre Event anhand der obigen Punkte erstellen
--> Organisieren wer was präsentiert
--> @Sponsoring: Bitte den möglichen Sponsoren so mitteilen und uns mitteilen, wenn sie etwas pitchen/vorstellen möchten

**Comment by jjerlich** [comment]
Pre-Event Timephrame festlegen: wann soll es diesen Event geben?

**Comment by culmat** [comment]
eventuell  bei trivadis?

**Comment by jjerlich** [comment]
Trivadis confirmed hosting the pre-event incl. Apero, Yeah!!

**Comment by jjerlich** [comment]
Date Options clear now - Decision awaited
16.11.2018
19.11.2018
20.11.2018

Org Details:
- Creative & casual meeting Room
- Apero with Italian Food provided by Trivadis

Agenda:
- Tech Input
- Data Sets at the Hack
- What it takes to do a Hack
- Examples from 2017 Teams

**Comment by jjerlich** [comment]
Decision/Entscheidung

Deployment Workshop
16.11.2018 Technik

Pre-Event ab 18:30 Beginn 
16.11.2018
Daten, Ideen, Kennen lernen, What it takes to succeed
Priska Fragen

**Comment by jjerlich** [comment]
Wer kann einen Beitrag am Pre-Event machen?

**Comment by jjerlich** [comment]
Anfrage zur Teilnahme ging raus
Christopher Zimmermann
Robin Freyburger, Actemium
Elizaveta Semenova

Absage
Priska Burkard 
Stefani -Gerber 

Partner
Caspar von Stümpnagel, Trivadis
Alexander Papezik, Trivadis
Tina Crameri www.projekt-blink.ch

Zugesagt haben:
Roland Brand
Ixchel Ruiz and Andres Almiray (Founders Hackergarten)
Dietrich Rordorf
Alexander Timmermans from PubTransViz - Prototyp fertig gestellt

Dabei vom Team
Matthias, Jonas und Jutta, Thomas angefragt

Jutta macht noch 2-3 Slides und moderiert mit Matthias
