### ISSUE TITLE
Sommer-Event

### ISSUE THREAD

**Issue by StanBarrows** [BaselHack/Verein#117]
Bier & ...

https://doodle.com/poll/hg8qvfrigu2yakwh

**Comment by StanBarrows** [comment]
No Power-Point Event

**Comment by StanBarrows** [comment]
Create a Doodle

**Comment by culmat** [comment]
von info@baselhack.ch an member@baselhack.ch (vereinsmitglieder) + helfer 
siehe https://drive.google.com/drive/folders/1I66C6GqjGPwaMSudDSy8hq9sssqSyX2-
https://github.com/BaselHack/verein/wiki/Team
