### ISSUE TITLE
Track Sponsors

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#12]
with status, on GoogleDrive

**Comment by teddybeaker** [comment]
Spreadsheet "Sponsoring_Status" gestartet in GoogleDrive, muss es aber noch besser ausarbeiten

**Comment by teddybeaker** [comment]
updated spreadsheet and status for two sponsors

**Comment by jjerlich** [comment]
Updated spreadsheet with Special Price information Kanton Basel Stadt

**Comment by teddybeaker** [comment]
can be closed once all payments arrived
