### ISSUE TITLE
Define duties for Jury members

### ISSUE THREAD

**Issue by mayvi** [BaselHack/Verein#126]
Jury mehr in den Event einbeziehen (Vorstellen während des Hacks und ein paar Stunden Anwesenheit sollte Pflicht sein) --> Christoph

**Comment by schmidchr** [comment]
in my opinion it will be difficult to find for the jury some renowned (-> busy) non-IT specialists (local economy, politics, education, ...) and also IT-professional, if we ask for a presence during a substantial part of the weekend!

**Comment by schmidchr** [comment]
We might ask if one member of the jury volunteers to briefly present the evaluation criteria at some early stage of the hacking
