### ISSUE TITLE
Email groups and contact sheets 

### ISSUE THREAD

**Issue by culmat** [BaselHack/Verein#13]
- team
- members

**Comment by culmat** [comment]
@BaselHack/mitglieder 
wir könnten auch einfach [team mentions](https://github.com/blog/1121-introducing-team-mentions) verwenden.
Dann bleibt die Info auch themen bezogen

**Comment by teddybeaker** [comment]
Finde ich gut, wenn wir alle Daten an einem Ort verwalten können. Würde in dem Fall auch gar keinen Mail-Verteiler erstellen. Wie könnte man alle ansprechen, also auch die nicht-Mitglieder?

**Comment by culmat** [comment]
Die mentions funktionieren mit Github teams. Wir können beliegibe Teams erstellen, aber nur, wenn wir die Github-UserIDs der Leute kennen. Von einigen Non-Members kennen wir sicher nur Email. Ich denke für team macht ein Kontakt-Sheet / Mailverteiler Sinn.

**Comment by teddybeaker** [comment]
@culmat : Wenn ich Personen beim Github hinzufüge, gebe ich die Gruppe "mitglieder" nur, wenn sie Vereinsmitglied sind? Bin etwas verwirrt wegen "members" und "mitglieder" :)

**Comment by culmat** [comment]
@teddybeaker ja das ist die Idee "mitglieder" =  vereinsmitglieder. Sollen wir die Gruppe umbennen?

**Comment by teddybeaker** [comment]
@culmat ja gern, das würde mich entwirren :) habe es grad geändert.

**Comment by teddybeaker** [comment]
Daten übernommen nach https://github.com/BaselHack/verein/wiki/Team und Mail-Verteiler team@baselhack.ch erstellt.
