### ISSUE TITLE
member

### ISSUE THREAD

**Issue by rordi** [BaselHack/Verein#136]
name: Dietrich Rordorf
email: drordorf@gmail.com
username: rordi

Habe am ersten BaselHack als Teilnehmer teilgenommen und würde nun gerne auf einer anderen Ebene zum BaselHack beitragen.

Grüsse,
Didi

**Comment by JJatsch** [comment]
ok

**Comment by mayvi** [comment]
yes, cool :-)

**Comment by culmat** [comment]
+1

**Comment by rordi** [comment]
Danke :)
