### ISSUE TITLE
member

### ISSUE THREAD

**Issue by sjoerd222888** [BaselHack/Verein#138]
name: Alexander Timmermans
email: alexander@timmermans.ch
username: sjoerd222888

Thx

**Comment by sjoerd222888** [comment]
I think I cannot at the label "member" myself, can I?

**Comment by culmat** [comment]
@sjoerd222888 willkommen
@StanBarrows kannst du bitte Alexander noch in die mailing-list member@baselhack.ch aufnehmen?
Bis bald.
Matthias

**Comment by JJatsch** [comment]
ok

**Comment by culmat** [comment]
+1

**Comment by mayvi** [comment]
thumbs up
