### ISSUE TITLE
Twitter Account Details

### ISSUE THREAD

**Issue by jjerlich** [BaselHack/Verein#141]
Liebe Leute, lieber Oliver!

Ich brauche nun wirklich dringend die Rückmeldung bzw. die Accountdaten von unserem Twitter Account. 

Nach vielen Emails haben wir ja zusammen rausgefunden, dass Valeria Can die Daten haben müsste.

Oliver schrieb "Valerie arbeitet bei der BKB. Ich habe sie in meiner LinkenIn Kontaktliste und frage sie mal. Zudem kann ich die Nachfolgerin von Valerie fragen, ob sie die Zugangsdaten hat. SIe hat zu Beginn auch im Social Media Bereich mitgearbeitet."

Bitte um Rückfrage und Zusendung der Daten !!!
DANKEEEE

**Comment by mayvi** [comment]
Valerie hat die Daten leider nicht. Hoffentlich hat sie die Nachfolgerin

**Comment by jjerlich** [comment]
- Matthias fragt bei Baloise nach

**Comment by OliverFritsch** [comment]
Valerie hat mir auch bestätigt, dass sie die Zugangsdaten nicht hat.
Ihre Nachfolgerin war/ist Lisa Hinterberger- Mit ihr hatte ich schon mal gesprochen und auch sie hatte damals die Daten nicht.


Am 09.10.2018 um 19:17 schrieb Jutta <notifications@github.com<mailto:notifications@github.com>>:


  *   Matthias fragt bei Baloise nach

**Comment by jjerlich** [comment]
Bitte @culmat und @JJatsch um Nachfrage bei euch intern nachfragen, wer da den Account bedienen könnte.
