### ISSUE TITLE
Marketing Boost

### ISSUE THREAD

**Issue by StanBarrows** [BaselHack/Verein#147]

**Comment by StanBarrows** [comment]
Bis zum nächsten Event:

Mail an Teilnehmer rauslassen für Marketing: @jjerlich & @StanBarrows 

- Adobe Infor für Marketing mit der Rechnung @JJatsch 
- Baloise Info geht noch raus @JJatsch @culmat 
- Basel Area Swiss @Brenzikofer 
- Standortförderung Basel Stadt @JJatsch 
- Facebook Marketing (Budget  50-100 CHF) @jjerlich 
- Google Adwords @StanBarrows (Gutschein 50CHF) 
- LinkedIn Teilen @alle
- Handelskammer @JJatsch 
- BaselStadt @mayvi 


Nächsten Donnerstag Teilnehmer fragen..

**Comment by rordi** [comment]
Es gibt einige Meetups in Basel, z.B. habe ich das DX Meetup angefragt, ob sie eine Folie zeigen können nächste Woche (https://www.meetup.com/de-DE/Digital-Experience-Group/). Gibt es sowas wie eine Folie mit den Key Facts die man erwähnen muss (Datum, Zeit, Ort, gratis Teilnahme, Sponsoren, etc.)?

Weitere Meetups in nächster Zeit in Basel mit relevanter Zielgruppe:
- https://www.meetup.com/de-DE/IoT-Basel/events/255228014/
- https://www.meetup.com/de-DE/Impact-Hub-Basel/events/254956610/
- https://www.meetup.com/de-DE/sfubsl/events/251981891/
- https://www.meetup.com/de-DE/Impact-Hub-Basel/events/252030054/

**Comment by StanBarrows** [comment]
@rordi 
Tagged mit @2019, müsste man sicher aufgreifen.
