### ISSUE TITLE
Create Community

### ISSUE THREAD

**Issue by jjerlich** [BaselHack/Verein#15]
The use of Meetup powered by BaselArea.swiss is being checked by Thomas

**Comment by sabinsc** [comment]
Next Open Stammtisch November 2017 http://www.staatskanzlei.bs.ch/opendataBS 
could be a "after BaselHack ist before the BaselHack" Open Stammtisch.

**Comment by jjerlich** [comment]
Great to have this set in terms of sustainability and continuation with BaselHack next year

**Comment by jjerlich** [comment]
In conversation on Twitter with following amplifiern:
@g33konaut 
@Archilogic3D
@loleg
@_sabin_
