### ISSUE TITLE
Mitgliedsantrag Patrick Strittmatter

### ISSUE THREAD

**Issue by strittmatter** [BaselHack/Verein#160]
Patrick Strittmatter
patrick.strittmatter@actemium.ch
github.com/strittmatter

Ich habe am diesjährigen BaselHack teilgenommen und wurde so auf diesen Verein aufmerksam. Gerne möchte ich meine Unterstützung anbieten und es würde mich freuen, sofern ich mich diesem Netzwerk anschliessen dürfte.

**Comment by StanBarrows** [comment]
Hoi Patrick,

Wir freuen uns über dein Interessen. 

Wir beginnen im neuen Jahr mit den Vorbereitungen für den BaselHack 2019 und einer Mitgliederversammlung. Gerne laden wir dich zum ersten Treffen im neuen Jahr ein. Weitere Details erfolgen via E-Mail.

Liebe Grüsse
Stan

**Comment by strittmatter** [comment]
@StanBarrows @culmat 
Gibt es bereits weitere Details zur morgigen Mitgliederversammlung? Ich habe leider keine E-Mail erhalten und bin hier (#162, [Generalversammlung-BaselHack-2019](https://github.com/BaselHack/Verein/wiki/Generalversammlung-BaselHack-2019)) leider auch nicht fündig geworden.

Liebe Grüsse
Patrick

**Comment by michelpfirter** [comment]
@culmat @StanBarrows 
Würde mich @strittmatter Frage gerne anschliessen :-)
Danke & Grüsse

**Comment by StanBarrows** [comment]
@michelpfirter , @strittmatter 

Liebe Mitgliederinnen und Mitglieder des Vereins BaselHack,
 
Es freut mich, Euch hiermit zur Vereinsversammlung 2019 einzuladen.
 
Diese findet statt:
 
Date: 5. Februar 2019
Time: 19:00 - 21:00
Location: BaselArea.swiss, Dufourstrasse 11, Basel; Raum Erasmus
 
Traktanden:
Wahl der Stimmzähler
Genehmigung des Protokolls der letzten Mitgliederversammlung
Genehmigung des Jahresberichts des Vorstands
Jahresbericht Finanzen und Genehmigung der Jahresrechnung 2018
Entlastung des Vorstandes
Genehmigung des Jahresbudgets 2019
Wahl des Vorstandes
Festsetzung des Mitgliedsbeitrages
Varia
Dokumente: https://github.com/BaselHack/Verein/wiki/Generalversammlung-BaselHack-2019
 
Dürfte ich Euch bitten, Eure Teilnahme zu bestätigen.
 
 
Vielen Dank!
 
Mit den besten Grüssen
Thomas Brenzikofer in Vertretung des Vorstands

**Comment by michelpfirter** [comment]
@StanBarrows Danke
