### ISSUE TITLE
19th February 2019 - Kick-Off BaselHack 2019

### ISSUE THREAD

**Issue by StanBarrows** [BaselHack/Verein#163]
### We proudly invite to the Kick-Off BaselHack 2019

**Date**: 19. Februar 2019
**Time**: 19:00 - 21:00
**Location**: to be defined

**Comment by culmat** [comment]
see https://docs.google.com/document/d/182XjqtvhqNeIV0MkHAKc0OJpb108N3Hg52pHZxNLPxQ/

**Comment by michelpfirter** [comment]
Hi, could some please be so kind and tell me where the kickoff will be and if 19:00 - 21:00 is still correct? Thanks

**Comment by strittmatter** [comment]
@michelpfirter 
Once again, we are looking for the same information :)

@StanBarrows @culmat
Could you please give us further details about the kickoff?

**Comment by StanBarrows** [comment]
@strittmatter , @michelpfirter 

Hier ein Reminder zum Kickoff BaselHack 2019
Date: 19. Februar 2019
Time: 19:00 - 21:00
Location: FHNW-Basel, Peter-Merian
Raum wird am Display im Eingang angezeigt.
Für freuen uns auf Dein kommen!
Das BaselHack Team
