### ISSUE TITLE
Baselhack: Event 2019 Date & Location

### ISSUE THREAD

**Issue by StanBarrows** [BaselHack/Verein#166]
Provisorische Daten für den BaselHack 2019

- [ ] 12. / 13. Oktober 2019
- [ ] 19. / 20. Oktober 2019
- [x] 2. / 3. November 2019
- [ ] 16. / 17. November 2019
- [ ] 23. / 24. November 2019

[Add Events to Calendar](https://teamup.com/ksjzsvygmvckdnpeii)

Location

Voltahalle 
kein internet, dezentral
11.10 bis 13.10, 900 CHF
41 61 275 96 53
Brunella Torres
brunella.torres at iwb.ch
            
AlteMarkthalle
41 78 823 49 78
Dominik Lüönd
dominik.lueoend at altemarkthalle.ch
im Nov 2019 nicht verfügbar
Raum ab ~4000 CHF ( ohne Verpflegung )

NOVAC-SOLUTIONS **Areal Basel Wolfareal / Güterbahnhof**
76 201 18 92 
Patrick Kruse
patrick.kruse at novac-solutions.com
 - Location ist verfügbar im November
 - Tische, Stühle & WLAN ist vorhanden
 - Beamer ist Fix installiert
 - Ausweichmöglichkeiten ins OfficeLap (Co-WorkingSpace)

Im August findet ein Hackathon der SBB statt.

**Smartcity labs
-> Jonas Jatsch, 
79 172 67 13, Anne-Claire Pliska.
Treffe mich am 03.07. 14 Uhr mit ihr. Hack im November wäre ok.**

https://iwbfilter4.ch/about/#vermietung
nur bis 2.00h, bis oktober :-/

impacthub
-> Matthias, Marina

**http://mitteldeck.ch**
Grundsätzlich haben wir noch freie Daten im November. Allerdings ist die Internet-Verbindung nicht sehr stark, weshalb ich unsicher bin ob dies für Ihre Zwecke ausreicht…

In der Beilage sende ich Ihnen die Dokumentation des Mitteldecks. Die Tagespauschale beträgt CHF 2’500.- (exkl. MwSt.) und beinhaltet Grund-Infrastruktur (Beleuchtung, Strom) sowie Reinigung. Gerne können wir Catering sowie Möblierung über externe Partner-Firmen koordinieren / organisieren. Selbstverständlich sind Sie jedoch frei eigene Lieferanten zu berücksichtigen.

**launchlabs** 
-> Jutta 
26/27.10 oder 09/10. 11
im Budget ;-) 
Termin

freies gymnasium
-> Sebastian

https://alteskraftwerk.ch/
-> Sebastian

http://oslostudios.ch/grundriss/
-> Sebastian

**Comment by JJatsch** [comment]
Mit Anne-Claire Pliska telefoniert. 79 172 67 13. Treffe mich nächsten Mittwoch um 14 Uhr mit ihr im SmartCityLab. Will noch jemand mitkommen?
Hack im November kein Problem, im August hosten sie schon einen anderen Hackathon.
