### ISSUE TITLE
TODO BaselHack 2019

### ISSUE THREAD

**Issue by culmat** [BaselHack/Verein#171]
1. Besichtigung ImpactHub - Stand der Dinge | @jjerlich , @culmat :heavy_check_mark: 
   1. Kreativ Material ( Flips, Stifte ) Impact Hub hat whiteboards, bitte keine Permanentmarker mitbringen :heavy_check_mark: 
1. Event koordination @culmat 
   1. [Helferplan](https://github.com/BaselHack/Verein/wiki/BaselHack-2019-supporters) & koordination, Brauchen wir Nachtwächter : nein --> mehr Helfer Nachfragen
   1. Sebastian (@StanBarrows )ist wenn gewünscht 48h am Hack Verfügbar
   1. Code für Tür / Aufbau / Abbau Besenrein / Müll / Dusche :heavy_check_mark: 
1. Essen   @strittmatter :heavy_check_mark: 
1. Sponsoren Abholen ( Job Wall, Coaches, Give Aways ) @JJatsch :heavy_check_mark: 
1. Reminder & Instruktionen an Teilnehmer @StanBarrows 
1. Bargeld Geld beschaffen für Depot-Rückgabe  Bitte 90 x 20CHF @StanBarrows mit @dariotodaro 
1. Deko & Wegweiser @culmat A0 kartoniert / laminiert?
1. BaselHack TShirts / Sticker / Gadgets @culmat :heavy_check_mark: 
1.  Jury  2 Jurymitglieder | POZ | ACP | IXCHELR | Luc Haldimann +1 & Geschenke Pigeonhole? @JJatsch  :heavy_check_mark:  +Dominick Boyle
1. Preise für Teilnehmer  | Trivadis Gutschein | Baloise Kick-Box| Impacthub CWS | 6 x Gadget | Budget @dariotodaro Task@StanBarrows | Urkunden Drive 
1.  Zeremonienmeister / [Slides für Pitching](https://github.com/BaselHack/Verein/tree/gh-pages/event) @jjerlich  & @culmat 
1.  Namesschilder & Teilnehmerlisten vor Ort @StanBarrows
1.  Reminder & Instruktionen an Teilnehmer @StanBarrows - 28.10.2019
   1. Lageplan | Google Maps Link

Ablauf
Check-In (Sebastian)

    Namensschilder
    Depot
    Anmeldung

**Comment by strittmatter** [comment]
Bzgl. Punkt 3. (Essen) siehe: [Catering](https://github.com/BaselHack/Verein/wiki/BaselHack-2019-supporters#catering---%EF%B8%8F--)
