### ISSUE TITLE
Neue Vereinsadresse 

### ISSUE THREAD

**Issue by culmat** [BaselHack/Verein#176]
Hallo Patrick, ciao Vorstände,

alles klar bei euch?

Wir sind von BaselArea angefragt die Adresse zu ändern und dies macht aus meiner Sicht Sinn.
 
Laut https://github.com/BaselHack/Verein/wiki/Mitgliederversammlung-BaselHack-2020 legen wir die Vereinsadresse zu ImpactHub.

Laut https://github.com/BaselHack/Verein/issues/173 sind die Kosten 30 CHF / Monat.

Laut https://www.baselhack.ch/imprint ist die Vereinsadresse "BaselHack, Dufourstrasse 11 4010 Basel "

- Haben wir den Briefkasten im Vertrag mit ImpactHub? Wenn ja wie ist die Kündigungsfrist?
 - Die Post bietet eine Vereinsadresse mit eigener PLZ für 20 CHF / Jahr an, siehe https://www.post.ch/de/empfangen/empfangsorte/vereinsadresse
- Ich bin für Vereinsadresse bei der Post, die bleibt dann stabil, ist billig und bequem (der Aktuar kriegt die Post direkt nach Hause)
- Da die Adressanpassung bereits durch die letzte GV genehmigt wurde und eine lästige Formalität ist, schlage ich vor, den Beschluss elektronisch an diesem Issue zu fassen.

Wer für Erstellung der Vereinsadresse bei Post.ch ist, bitte diesem Issue :+1: geben.

Beste Grüße,

Matthias

**Comment by culmat** [comment]
:+1:

**Comment by strittmatter** [comment]
👍 ist i.O. für mich - auch wenn die separate Ansprache mich etwas irritiert hat. Ich hoffe ich habe hier nichts verpasst? 🤔

**Comment by StanBarrows** [comment]
Geht i.O. für mich auch wenn ich gerade auf der Leistung stehe wie ein "Daumen Hoch" smiley geht.

**Comment by dariotodaro** [comment]
👍 Super
