### ISSUE TITLE
member

### ISSUE THREAD

**Issue by juengls** [BaselHack/Verein#18]
Stephan Jüngling
stephan.juengling@fhnw.ch
juengls

**Comment by teddybeaker** [comment]
👍

**Comment by sabinsc** [comment]
https://github.com/sabinsc
Sabine Schneeberger, Leiterin Web-Entwicklung
Präsidialdepartement des Kantons Basel-Stadt
Staatskanzlei | Kommunikation
Marktplatz 9 | CH-4001 Basel
Telefon: +41 61 267 69 64
sabine.schneeberger@bs.ch
www.staatskanzlei.bs.ch/ogd
https://twitter.com/hashtag/opendataBS

**Comment by teddybeaker** [comment]
@Brenzikofer , @culmat : brauche hier noch ein OK von einem von euch :smiley:

**Comment by Brenzikofer** [comment]
OK für mich
