### ISSUE TITLE
Member Valentino Rusconi

### ISSUE THREAD

**Issue by valentinorusconi** [BaselHack/Verein#181]
Name: Valentino Rusconi
Email: valentino.rusconi@hey.com
Github : valentinorusconi

**Comment by rordi** [comment]
Hi Valentino,

Thank you for your interest to join the Verein BaselHack. According to the bylaws two members of the board need to approve the membership request, which has happened with the two upvotes on your request. Welcome to the association! The BaselHack will take place on 11 & 12 September 2021 (more infos to follow soon). Hope to see you there.

**Comment by rordi** [comment]
Added per https://github.com/BaselHack/Verein/wiki/Mitglieder/399721f00233d82ad9941c2f0d8702775e836906
