### ISSUE TITLE
Rechnung | BaselHack

### ISSUE THREAD

**Issue by StanBarrows** [BaselHack/Verein#183]
Hoi Zusammen

Versuch Nr. 5 seit dem 04.01.2021.

Liebe Grüsse
 Sebastian Fix

**Comment by dariotodaro** [comment]
Salli Sebastian, die zwei letzten Emails hab ich nicht bekommen. Matthias und ich haben dir am 17/03/2021 mal noch geantwortet, seit dem hab ich nichts mehr bekommen :P hattest du diese email gesehen? Lieber Gruss Dario

**Comment by dariotodaro** [comment]
Jetzt hab ich grad noch gecheckt warum, weil die Emails an info@ gingen 😂 Entschuldige vielmals, ich hab die Rechnung jetzt beglichen ;) glg

**Comment by StanBarrows** [comment]
Mercy =)
