### ISSUE TITLE
New Member: Jack Wilkinson

### ISSUE THREAD

**Issue by wilkinsonjack1993** [BaselHack/Verein#184]
Name: Jack Wilkinson
Email: wilkinsonjack1993@gmail.com
Github : wilkinsonjack1993

**Comment by rordi** [comment]
Hi Jack,

✅ You got two votes from the board members. Welcome as a new member of the BaselHack Verein! The annual general assembly of the association will be on 8. February 2022 19:00 to 21:00 at MDPI AG, Reinacherstrasse 129, Basel, Switzerland. We will send out the invites this week including the agenda.
