### ISSUE TITLE
member

### ISSUE THREAD

**Issue by Anphisa** [BaselHack/Verein#185]
Name: Phaina Koncebovski
Email: (habt ihr hier wirklich Klartext eure Emails stehen? Werdet ihr nicht total zugespammt?)
Github : Anphisa

Hallo! Ich war beim BaselHack 2022 dabei und hatte viel Spass. Ich habe keine Ahnung, was meine zeitliche Verfügbarkeit sein wird, aber wenn ich Zeit habe, würde ich gerne bei euch mitmachen!

**Comment by rordi** [comment]
Hi Phaina,

✅ You got two votes from the board members. Welcome as a new member of the BaselHack Verein! The annual general assembly of the association will be on 8. February 2022 19:00 to 21:00 at MDPI AG, Reinacherstrasse 129, Basel, Switzerland. We will send out the invites this coming week including the agenda.
