### ISSUE TITLE
New Member: Yasin Gündüz

### ISSUE THREAD

**Issue by yguenduez** [BaselHack/Verein#186]
Hello there,

I have been at the Baselhack 22 and quite liked it.
If I could spare some time, I can help organize the BaselHack 23 :).
See you soon - in any case.

Name: Yasin Gündüz
mail: yasinguenduez1@gmail.com

**Comment by rordi** [comment]
Hi Yasin,

✅ You got two votes from the board members. Welcome as a new member of the BaselHack Verein! The annual general assembly of the association will be on 8. February 2022 19:00 to 21:00 at MDPI AG, Reinacherstrasse 129, Basel, Switzerland. We will send out the invites this coming week including the agenda.
