### ISSUE TITLE
member Sabine Schneeberger

### ISSUE THREAD

**Issue by sabinsc** [BaselHack/Verein#19]
https://github.com/sabinsc

Sabine Schneeberger, Leiterin Web-Entwicklung
Präsidialdepartement des Kantons Basel-Stadt
Staatskanzlei | Kommunikation
Marktplatz 9 | CH-4001 Basel
Telefon: +41 61 267 69 64
sabine.schneeberger@bs.ch
www.staatskanzlei.bs.ch/ogd
https://twitter.com/hashtag/opendataBS

**Comment by teddybeaker** [comment]
👍

**Comment by sabinsc** [comment]
moved to #18 member...

**Comment by teddybeaker** [comment]
Hallo @sabinsc , danke für deinen Mitgliederantrag. Die anderen Vorstandsmitglieder sind grad in den Ferien, habe ihn ihnen aber zugeteilt.

**Comment by jjerlich** [comment]
Ganz herzlichen Dank @sabinsc für unser Erstgespräch, die Ausschreibung des Special Prices für euer #opendata Projekt und die gestrige Sitzung zur Sichtung der vorhandenen Daten mit Andres Gartmann

**Comment by Brenzikofer** [comment]
👍

**Comment by teddybeaker** [comment]
https://github.com/BaselHack/verein/wiki/Mitglieder ergänzt

**Comment by sabinsc** [comment]
Austritt
Liebe Basel Hackers. Hiermit ziehe ich mich zurück aus dem Verein. Das OGD-Pilotprojekt 2017/18 ist beendet, s. [www.staatskanzlei.bs.ch/ogdBS](https://www.staatskanzlei.bs.ch/ogdBS). Danke für euer Engagement. Herzlich, sabin
