### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by AndrejLauperBBZBL** [BaselHack/Verein#190]
I'm Andrej from Basel.
I would be interessted to help in BaselHack

Name: Andrej Lauper
E-Mail: andrej.lauper@endress.com

**Comment by yguenduez** [comment]
Hey Andrej,

nice to see that you want to join BaselHack. And as more than two members upvoted your issue, you are in!
We will have our GV on February 15th (place and exact time are TBD). 
You will get an invitation via mail soon. Until then a merry Christmas with your loved ones and a happy new 2024.

Best
Yasin
