### ISSUE TITLE
Member Marco Inniger

### ISSUE THREAD

**Issue by InnigerM** [BaselHack/Verein#191]
Hi there,
Thought I might join the baselhack association. My email is marco@inniger.email.
Let me know if you need anything else.

Cheers
Marco

**Comment by yguenduez** [comment]
Hey Marco,

Nice to see that you are joining us :). As more than two fellas upvoted, you are now in.
We will have our GV on February 15th. The place and time (probably evening) are TBD.
You will get an official invitation soon. Till then a merry Christmas and a happy new 2024.

Best
Yasin
