### ISSUE TITLE
Kontaktdaten aus GoogleDocs an Thomas schicken

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#21]

**Comment by jjerlich** [comment]
Sent to Thomas via Email

**Comment by jjerlich** [comment]
Alle Leute wurden von mir angeschrieben und informiert. Habe auch 2 bereits getroffen :-)

**Comment by jjerlich** [comment]
Alle Leute wurden von mir angeschrieben und informiert. Habe auch 2 bereits getroffen :-)
