### ISSUE TITLE
Redirect baselhack.ch/registration einrichten

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#22]
Sobald die  URL von Thomas erhalten

**Comment by martinchristen** [comment]
**Backup für Anmeldung**
https://ti.to/baselhack/baselhack-2017

Einbinden mit
<link rel="stylesheet" type="text/css" href='https://css.tito.io/v1.1' />
<script src='https://js.tito.io/v1' async></script>
<tito-widget event="baselhack/baselhack-2017"></tito-widget>

**Comment by martinchristen** [comment]
sorry, einbinden mit:

```
<link rel="stylesheet" type="text/css" href='https://css.tito.io/v1.1' />
<script src='https://js.tito.io/v1' async></script>
<tito-widget event="baselhack/baselhack-2017"></tito-widget>
```

**Comment by teddybeaker** [comment]
Anmeldung über BaselAreaSwiss ( https://www.baselarea.swiss/de/baselarea-swiss/channels/innovation-events/2017/10/baselhack-der-hackathon-fuer-die-region-basel.html) eingerichtet
- Weiterleitung unter baselhack.ch/registration
- Link in Webseite korrigiert

**Comment by teddybeaker** [comment]
@martinchristen: herzlichen Dank für das Einrichten von Tito. Da die Registrierung über BaselArea.swiss zeitnah aufgeschaltet wurde brauchen wir Tito doch nicht. Kannst du kontrollieren, dass wir nur "eigene" Anmeldungen drin haben und es dann deaktivieren? Nicht dass der Link dann plötzlich doch noch irgendwo rumschwirrt und wir Anmeldungen übersehen.

**Comment by martinchristen** [comment]
ti.to gelöscht

**Comment by teddybeaker** [comment]
add separate redirect for EN-version (/registration.en would be compliant to naming of index.html index.en.html; check if that works)

**Comment by teddybeaker** [comment]
fixed
