### ISSUE TITLE
Tool to manage Teams and Status during Hackathon

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#25]
Inquire about costs

**Comment by jjerlich** [comment]
Here is the answer from https://github.com/loleg, here is also Dribdat https://github.com/loleg/dribdat

"Dribdat is open source and relatively straightforward to deploy, so you could just follow the online instructions to get it up and running, a basic Heroku instance for 6 months would cost around 300 CHF. 

If you'd like help setting it up and making sure it's extra accessible and performant during the event, then I would budget about 5-6 hours of developer time, or around 1K. If you would like to customise it in some way, like integrating with your Slack channel, adding bots, showing live results on your main website, changing the look and feel, etc., I'd recommend adding a working day. "

Awaiting reply with resources available for set up and integration / budget approval

**Comment by schmidchr** [comment]
'Nice-to-have':  'simple' app to digitally manage the votes of the jury
- enabling rapid aggregation of scores to determine the winning project (individual votes private to jury) 
- stable & open-source code

I could not find a description of such a jury functionality withing Dribdat, potential alternatives:
- AwardForce (https://www.awardforce.com/)
- weemss (https://weemss.com/awards/#features) <br>
=> yet both rather complex, 'all-inclusive' solutions, not sure if they are meeting our needs?

**Comment by andgart** [comment]
Dear Oleg,

I hope you are well! 

I write you about dribdat and your email from beginning of August. Jutta couldn’t attend the baselhack meeting yesterday, so I temporarely take care about this topic. 

Is there an option for simply manage the votes of a jury in your app? Would it be difficult to add this? 

You can contact me also on my mobile: 076 319 96 15.

Best wishes,
Andres

**Comment by andgart** [comment]
Dear Andres,

There is a backend for voting, but the feature was never completely developed so the code is out of the production version. 

Nevertheless Dribdat helps you to put all the projects in one place, and then print out all the details on one page or generate a spreadsheet (CSV export) which you can distribute to the judges along with some scoring columns as a simple option.

Cheers,
Oleg

**Comment by andgart** [comment]
meeting 2.10.2017 - decision was made not to use a management system
