### ISSUE TITLE
OnSite Planning

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#28]
Track, who of the team plans to participate and who is available for staff

**Comment by teddybeaker** [comment]
https://github.com/BaselHack/verein/wiki/Staff---Planning

**Comment by teddybeaker** [comment]
@BaselHack/vereinsmitglieder: please fill out https://github.com/BaselHack/verein/wiki/Staff---Planning whether you want to participate at BaselHack or are available as staff.

**Comment by JJatsch** [comment]
Hi Steffi

 

Ich kann soweit ich sehe das Wiki nicht bearbeiten. Bin an allen 3 Tagen als Staff verfügbar.

 

Liebe Grüsse

Jonas

 

Gesendet: Mittwoch, 02. August 2017 um 14:08 Uhr
Von: "Stefani Gerber" <notifications@github.com>
An: BaselHack/verein <verein@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [BaselHack/verein] OnSite Planning (#28)


@BaselHack/vereinsmitglieder: please fill out https://github.com/BaselHack/verein/wiki/Staff---Planning whether you want to participate at BaselHack or are available as staff.

**Comment by teddybeaker** [comment]
Hoi @JJatsch 
Habe es eingetragen. Deine Einladung zu Github ist noch hängig, evtl. musst du die zuerst annehmen. Habe sie nochmals verschickt. Melde dich, falls du kein E-Mail erhältst.
LG, Steffi

**Comment by JJatsch** [comment]
Hoi Steffi

 

Ist es weiterhin hängig? Ich habe ansonsten noch keine Bestätigungsmail von Github bekommen?

 

Welche Adresse hast du eingeladen? Die hier oder die Baloise Adresse?

 

Liebe Grüsse

 

Jonas

 

Gesendet: Freitag, 04. August 2017 um 15:43 Uhr
Von: "Stefani Gerber" <notifications@github.com>
An: BaselHack/verein <verein@noreply.github.com>
Cc: JJatsch <jonasjatsch@gmx.net>, Mention <mention@noreply.github.com>
Betreff: Re: [BaselHack/verein] OnSite Planning (#28)


Hoi @JJatsch
Habe es eingetragen. Deine Einladung zu Github ist noch hängig, evtl. musst du die zuerst annehmen. Habe sie nochmals verschickt. Melde dich, falls du kein E-Mail erhältst.
LG, Steffi

**Comment by teddybeaker** [comment]
Hoi @JJatsch 
Ja, du bist weiterhin unter "pending invitations". Sehe nur deinen Github-Account, nicht welche E-Mail-Adresse dahinter ist. Wenn du dich auf Github einloggst und danach auf https://github.com/orgs/BaselHack navigierst, siehst du dann die Einladung für das Repo? (siehe Screenshot auf https://stackoverflow.com/questions/34020327/cant-find-github-invitation-to-join-repo)

Liebe Grüsse,
Steffi
