### ISSUE TITLE
Insurance: do we need one?

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#34]
- können wir jede Haftung ablehnen?

->Oliver

**Comment by mabrimo** [comment]
- wir sollten die Pro und Cons abwägen, die Versicherung bei der Basler abzuschliessen, Pro ist sicherlich, dass wir Chancen auf Rabatt hätten und hohe Kulanz im Schadenfall erwarten können. Sollte es zum Härtefall kommen stehen aber im schlimmsten Fall indirekt Basler gegen Basler vor Gericht...

- ggf. lohnt sich eine Jahresvereinsversicherung (im Vergleich zu einer Eventversicherung), da unser Event in die Limiten der normalen Jahrespolicen reinfällt

-  meist sind Schäden an Mietobjekten ausgeschlossen, wir müssen schauen, ob man diese Deckung einschliessen kan

**Comment by teddybeaker** [comment]
Brauchen wir nicht, da Schäden an Infrastruktur/Gebäuden meist sowieso ausgeschlossen wird. Personenunfälle sind über die Versicherung der Teilnehmer abgedeckt.
