### ISSUE TITLE
Jury

### ISSUE THREAD

**Issue by culmat** [BaselHack/Verein#37]
People and judging criteria
see [https://github.com/BaselHack/verein/wiki/Rules]

**Comment by teddybeaker** [comment]
according to sponsoring: someone from Baloise 😄

**Comment by teddybeaker** [comment]
criteria for jury members (~5 persons):
- diverse (gender, language, Branche)

criteria for topics:
- innovationsgehalt
- potential / marktpotential / machbarkeit

**Comment by mayvi** [comment]
I asked Thomas Berger, IT-Leader of Kanton Basel-Stadt, if he would join us as Jury member. He accepted and he'll confirm it in the next days if his agenda allows it ;-)

**Comment by schmidchr** [comment]
to summarize above:

minimal Task of jury members:
	to evaluate each of the 5-20 topics at the final presentation on Sunday Oct-29 from 16 - 18h

Jury members:
	aiming at 5 personalities with interest and competences in software development in the Basel area 
	representing sponsors (Baloise Insurance, ...)
	aiming at some diversity in specializations, gender, languages
	→ see on GoogleDocs a list of potential candidates for tracking of invitations (thanks @mayvi )

 criteria for evaluation of topics:
	→ see draft on GoogleDocs
	finalized scoring sheet to be provided to jury members (somewhat 'objective' and standardized scoring facilitates consensus finding within jury)

**Comment by schmidchr** [comment]
@Brenzikofer : hints for jury members? to obtain some diversity in specializations & gender! see table in GoogleDoc 
https://docs.google.com/document/d/1Ux93784oH4tT1mD9iUcaFjRFW4qzIuwAWjLSnFsepn0/edit#

@culmat : any updates for the jury member(s) from Baloise? Ideally also available to share some experience from the BaloiseHack.

@mayvi : any news concerning your invitation to the jury?

**Comment by schmidchr** [comment]
see also issue #52 for planing of awards

**Comment by schmidchr** [comment]
@JJatsch : thanks for the additions to the draft for evaluation criteria: https://docs.google.com/document/d/1F8OO1vJ2NcgjGYBsoviIWYS1c2sz-ZakBJSUlm8VhFs/edit#

-> we will move on to paper-based evaluation sheets 

any additional hints for jury members? to obtain some diversity in specializations & gender! jury member from Baloise? Ideally also available to share some experience from the BaloiseHack.
 see table in GoogleDoc
https://docs.google.com/document/d/1Ux93784oH4tT1mD9iUcaFjRFW4qzIuwAWjLSnFsepn0/edit#

**Comment by schmidchr** [comment]
@culmat @teddybeaker :
Is it feasible to ask jury members (and coaches) to fill a brief description of their person on a corresponding wiki page on https://github.com/BaselHack/BaselHack2017/wiki/Jury-members-BaselHack2017, and then eventually transfer the content to a static website https://baselhack.ch/

**Comment by schmidchr** [comment]
@JJatsch : any updates on the name of the jury member from Baloise?

**Comment by JJatsch** [comment]
@schmidchr no, not yet.

**Comment by teddybeaker** [comment]
@schmidchr : I could help with asking the people and with putting the content onto the static website (baselhack.ch), or linking from there to the github, whichever is easier.
