### ISSUE TITLE
member 

### ISSUE THREAD

**Issue by schmidchr** [BaselHack/Verein#38]
Christoph Schmid
Christoph-D.Schmid@swissonline.ch
schmidchr

**Comment by teddybeaker** [comment]
Hallo @schmidchr 
Danke für dein Interesse. Falls du nicht bereits über ein bestehendes Team-Mitglied zu uns gestossen bist: wir treffen uns das nächste Mal kommenden Montag (21.8.) von 16:00-17:30 bei Baloise (Aeschengraben 21, 4051 Basel).
Viele Grüsse und bis hoffentlich bald,
Steffi

**Comment by culmat** [comment]
:+1: 
Willkommen Christoph!
@teddybeaker : kannst du Christoph bitte zu  team@baselhack.ch hinzufügen?
Den rest hab ich gemacht - hoffe ich habe nichts vergessen ;-)

**Comment by schmidchr** [comment]
Danke @teddybeaker <https://github.com/teddybeaker> und @culmat für die
diversen Einladungen und Informationen.

Ich werde versuchen, am Treffen am Montag teilzunehmen, und dabei
herauszufinden, welche Beiträge ich zu BaselHack leisten kann?

PS. Antwort auf geschlossenes issue eigentlich ein no-go :(, hoffentlich
als 'Anfängerfehler' toleriert :)

**Comment by teddybeaker** [comment]
👍 
Im Mail-Verteiler aufgenommen.

@culmat : Hast an alles gedacht 😄 Habe unten auf der Teamseite eine Checkliste angehängt für Neuzugänge (https://github.com/BaselHack/verein/wiki/Team#admin-add-a-new-team-member). Analog für neue Vereinsmitglieder (https://github.com/BaselHack/verein/wiki/Mitglieder#admin-add-new-vereinsmitglied).
