### ISSUE TITLE
Spread the word!

### ISSUE THREAD

**Issue by mabrimo** [BaselHack/Verein#39]
Application link and info text online:
https://github.com/BaselHack/verein/wiki/Infotext

@BaselHack/Vereinsmitglieder: Spread the word 
@OliverFritsch kannst du es bitte mit lieben Gruss von mir an Michelle A. weiterleiten? Danke

**Comment by schmidchr** [comment]
generated GoogleDoc "Announcement_tracking" to keep track of sent announcements of BaselHack 2017 event
→ to minimize ‚unprofessional‘, widely divergent announcements from multiple contact persons to identical recipients

**Comment by teddybeaker** [comment]
@culmat : gibt es eine Möglichkeit, über BaselOne noch Leute zu erreichen?
