### ISSUE TITLE
Social Media

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#4]
for Twitter, Xing, LinkedIn

-> Valérie, Oliver

**Comment by OliverFritsch** [comment]
Xing Eventseite: https://www.xing.com/events/baselhack-1833608

Linkedin Gruppe: https://www.linkedin.com/groups/8615464

**Comment by teddybeaker** [comment]
@valeriecan: kannst du bei Facebook und Twitter @jjerlich  als Admin freischalten? Merci

**Comment by jjerlich** [comment]
Ich habe keinen Zugang zu den beiden Accounts

**Comment by teddybeaker** [comment]
@lisaandrea : kannst du Jutta als Admin freischalten?

**Comment by jjerlich** [comment]
Bitte alle Account Daten im GoogleDrive Accounts dokumentieren.

**Comment by lisaandrea** [comment]
@jjerlich Diese sind dokumentiert. Ich kann dich nicht "als Freund hinzufügen", um dich als Admin freizuschalten müssten wir Facebook-Freunde sein. Kannst du mich adden? "Lisa-Andrea Hinterberger"

**Comment by teddybeaker** [comment]
@jjerlich: kannst du dich mit "Lisa-Andrea Hinterberger" befreunden auf Facebook, damit sie dich auch als Admin freischalten kann? Merci

**Comment by jjerlich** [comment]
Erledigt, danke.
Twitter wäre noch, funktioniert jetzt schon sehr gut. Danke an Lisa-Andrea Hinterberger.
