### ISSUE TITLE
Check Registration Admin Tool Access for baselhack members

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#40]
Find out if there is a way to let other baselback members check and see the state of registrations.
Background of the issue / requirement is, that a broader group of people can manage registrations and no bottleneck occurs. Thanks

**Comment by Brenzikofer** [comment]
We have 36 Registrations now. 
We could have a talk about the possibilites to check registration, although I think this would be to much of an effort.... Easier just to give the numbers on  a eekly basis...

**Comment by teddybeaker** [comment]
We can also ask Nadine Bailleux
