### ISSUE TITLE
contact data-provider

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#42]
* BaselStadt can provide dataset
* Vivienne has various contacts

track on:
https://github.com/BaselHack/BaselHack2017/wiki/Topics

-> Vivienne

**Comment by andgart** [comment]
Am 10.08.2017 um 23:06 schrieb Andres Gartmann <andres.gartmann@gmx.ch>:

Liebe Sabin,

wie besprochen anbei eine Liste von gewünschten Daten. Unter dem Blatt "Selektierte Ideen" sind die letzten Montag besprochenen Ideen aufgelistet. Für jede habe ich versucht die entsprechend nötigen Daten aufzuführen. Die dunkelgelb markierten wären nötig zu besorgen, die hellgelben sind im geoviewer auffindbar.

Unter dem Blatt "nötige Daten" habe ich die von Dir gewünschte Liste zusammengestellt, inklusive Auflösung und weitere Details. Mögliche Formate habe ich aufgeführt, einfach das was am einfachsten und schnellsten geht. Ich würde diese dann entsprechend den Bedürfnissen umwandeln. Wir können auch mit grossen Datenmengen (TBs) ohne weiteres umgehen.

Für Rückfragen stehe ich Dir gerne auch unter 076 319 96 15 zur Verfügung.

Herzliche Grüsse und Danke für Deine Bemühungen

Andres

CC an Martin Christen Dozent für geo-Daten an der FHNW

CC an Vivienne Mayer


<Daten data driven challanges.xlsx>



[Daten data driven challanges.pdf](https://github.com/BaselHack/verein/files/1242033/Daten.data.driven.challanges.pdf)

**Comment by sabinsc** [comment]
-----Ursprüngliche Nachricht-----
Von: Schneeberger, Sabine 
Gesendet: Freitag, 11. August 2017 12:08
An: 'Andres Gartmann'
Cc: Christen, Martin; Mayer, Vivienne; Jutta Jerlich
Betreff: AW: Daten BS

Lieber Andres

Danke für die Zusammenstellung. Werde die Hebel möglichst in Bewegung setzen. Z.T. muss ich noch die zuständigen Stellen ausfindig machen (@ Vivienne rufst mich mal an, vielleicht gibt's bei euch noch Infos dazu?). 
Bin gespannt, was wir zusammentragen können....

Sonnige Grüsse
sabin

**Comment by sabinsc** [comment]
Lieber Andres

Ich habe die Rückmeldung vom Amt für Mobilität erhalten, dass sie Daten wie folgt für den BaselHack zur Verfügung stellen können:

Verkehrszähldaten (Vergangenheitsdaten, etwa ein Monat zurück) in Stundenauflösung für den MIV, Velos und Fussgänger

Weitere Infos, wo was gesammelt wird:
http://www.mobilitaet.bs.ch/gesamtverkehr/verkehrskennzahlen/verkehrszaehlung.html
http://www.mobilitaet.bs.ch/menus/flyup-statistiken.html



Kannst du mir präzisieren, was und für welchen Zeitraum ich vorbereiten lassen soll, dann laden wir das zum BaselHack auf github hoch.
Danke und Gruss
sabin



Von: andgart [mailto:notifications@github.com]
Gesendet: Dienstag, 22. August 2017 14:47
An: BaselHack/verein
Cc: Subscribed
Betreff: Re: [BaselHack/verein] contact data-provider (#42)


Am 10.08.2017 um 23:06 schrieb Andres Gartmann andres.gartmann@gmx.ch<mailto:andres.gartmann@gmx.ch>:

Liebe Sabin,

wie besprochen anbei eine Liste von gewünschten Daten. Unter dem Blatt "Selektierte Ideen" sind die letzten Montag besprochenen Ideen aufgelistet. Für jede habe ich versucht die entsprechend nötigen Daten aufzuführen. Die dunkelgelb markierten wären nötig zu besorgen, die hellgelben sind im geoviewer auffindbar.

Unter dem Blatt "nötige Daten" habe ich die von Dir gewünschte Liste zusammengestellt, inklusive Auflösung und weitere Details. Mögliche Formate habe ich aufgeführt, einfach das was am einfachsten und schnellsten geht. Ich würde diese dann entsprechend den Bedürfnissen umwandeln. Wir können auch mit grossen Datenmengen (TBs) ohne weiteres umgehen.

Für Rückfragen stehe ich Dir gerne auch unter 076 319 96 15 zur Verfügung.

Herzliche Grüsse und Danke für Deine Bemühungen

Andres

CC an Martin Christen Dozent für geo-Daten an der FHNW

CC an Vivienne Mayer

Daten data driven challanges.pdf<https://github.com/BaselHack/verein/files/1242033/Daten.data.driven.challanges.pdf>

**Comment by sabinsc** [comment]
Plattform für Datasets https://github.com/StakaBS/BaselHack

**Comment by andgart** [comment]
Liebe Sabin,

danke für die erfreuliche Mitteilung.

Von Seiten einer Datenanalyse = Applikation: Stündlich aggregierte Werte aufgeteilt nach Kategorien für einen Zeitraum mit möglichst vielen aktiven Beobachtungen über einen kontinuierlichen Zeitraum = Möglichst wenig Datenlücken an möglichst vielen Punkten über möglichst viele unabhängige kontinuierliche Zeiträume.

anders formuliert:
- stündliche Werte
- aufgeteilt nach MIV, Velos und Fussgänger
- für alle Dauerzählstellen
- jeweils für 1 Woche

=> Werte in Form: Datum, von Uhrzeit bis Uhrzeit (inkl. Zeitzone (=Sommer/Winterzeit)), # Werte pro Kategorie

Toll wäre natürlich dies für ein ganzes Jahr zu erhalten (Damit liessen sich Effekte übers Jahr, wie Ferien, Wetter, Jahrszeit, Wochentag, etc. für z.B. ein Fussgänger- oder Velo-routing überlegen). Alternativ als nächstes für ein Jahr jeden Monat 1.Woche und 3. Woche, danach nur 1. Woche, Jeden zweiten Monat 1. Woche, etc.

Falls die Daten zu gross für github werden, können wir dies anders lösen (je nach vorhandenem Format (DBMS oder Dateien) bereite ich einen enstprechenden Speicher-Server zusammen mit Martin für den Hack vor und wir veröffentlichen die Metadaten der Daten auf github).

Reicht Dir die Antwort? Andernfalls kannst Du mich unter 076 319 96 15 erreichen.

Liebe Grüsse

Andres

**Comment by mayvi** [comment]
Bisherige Anfragen und Antworten
- Zentrale Informatik BL: Absage
- Amt für Informatik SO: Antwort ausstehend
- Swisscom: Absage
- Post: Antwort Absage
- UniBasel: Interesse da, Antwort ausstehend --> Update: Eher interessiert an Teilnahme, nicht als Datengeber
- Trivadis: Interesse da, Antwort ausstehend

**Comment by andgart** [comment]
Sitzung 18.09.2017:
Daten, welche "rechtzeitig" (bis 2 Wochen vor Anlass an data@baselhack.ch) kommen, werden wir  unterstützen, dass Sie am Hack zugänglich sind. Gepitch müssen sie von den Teilnehmern werden.

**Comment by andgart** [comment]
Das Tiefbauamt hat uns darauf hingewiesen, dass es gemäss Verordnung nicht zulässig sei, den Abfallsack vor 19:00 Uhr, bzw. nach 7 Uhr auf die Strasse runter zu stellen und bittet darum, keine Applikation zu entwickeln, die dieser Verordnung entgegensprechen würde.
 
Sonnige Grüsse
Sabine Schneeberger

**Comment by andgart** [comment]
[Daten data driven challanges rev 20170925.pdf](https://github.com/BaselHack/verein/files/1328658/Daten.data.driven.challanges.rev.20170925.pdf)

**Comment by sabinsc** [comment]
Verkehrszählung 2016, Fussgänger, Velo, Motorisierter Individualverkehr 2016 erhalten und hochgeladen auf: https://github.com/StakaBS/BaselHack

**Comment by andgart** [comment]
[Datenbesprechung 20171016.pdf](https://github.com/BaselHack/verein/files/1387790/Datenbesprechung.20171016.pdf)
