### ISSUE TITLE
read permissions GoogleDocs

### ISSUE THREAD

**Issue by schmidchr** [BaselHack/Verein#43]
at present anyone with the link can access (all of?) the documents on GoogleDocs.
Would it for some 'sensitive' documents (passwords, accounts, phone numbers, ...) make sense to restrict access to registered team members?
(may require to manually add/remove people!)

**Comment by teddybeaker** [comment]
thanks @schmidchr. I changed the permissions of the top-level folder, will have to check if that applies to the individual files automatically another time.

**Comment by teddybeaker** [comment]
checked some files on the lower levels and the permission seems to propagate.
