### ISSUE TITLE
member: StanBarrows; genusshaus

### ISSUE THREAD

**Issue by StanBarrows** [BaselHack/Verein#44]
name: Sebastian
email: sebastian.fix@smartgate.ch
Github-username: StanBarrows

**Comment by StanBarrows** [comment]
name: Oliver
email: oliver.reist@smartgate.ch
Github-username: genusshaus

**Comment by teddybeaker** [comment]
Hallo Sebastian und Oliver
Herzlichen Dank für euer Interesse! Ich werde euch gleich noch die Einladung zu unserer nächsten Sitzung weiterleiten und würde mich freuen, euch dort persönlich kennenzulernen.
Viele Grüsse,
Steffi

**Comment by teddybeaker** [comment]
@StanBarrows, @genusshaus : habe euch folgendermassen erfasst:
- github (müsst ihr noch bestätigen)
- Slack
- GoogleDrive
- Mailverteiler (team@baselhack.ch)

@culmat / @Brenzikofer : bräuchte noch ein OK von einem von euch für den Mitgliederantrag

**Comment by culmat** [comment]
👍

**Comment by teddybeaker** [comment]
@StanBarrows , @genusshaus : so, jetzt seid ihr auch Vereinsmitglieder 😄 Den Mitgliederbeitrag von 1CHF könnt ihr entweder überweisen (CH77 0076 9430 6005 0200 1) oder @culmat in bar geben.
