### ISSUE TITLE
Brainstorming Topic

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#48]
Sebastian und Oliver von smartgate dazunehmen

**Comment by schmidchr** [comment]
etwas 'brainstorm' zu diesem GoogleDoc hinzugefügt:
https://docs.google.com/document/d/1dIyqc_vnjM2LXwDOuPZACv4o1mR27DaLyCJkj7SQvxg

**Comment by teddybeaker** [comment]
contact also @Brenzikofer for infos on other suggestions

**Comment by schmidchr** [comment]
Please fill this [doodle](https://doodle.com/poll/32a2t3pnm6e9ukwa) to determine a suitable time point for a brainstorm discussion to generate template(s) for a teaser description of projects on the [github site](https://github.com/BaselHack/BaselHack2017/wiki/Topics).

tentative agenda:
- overview on already submitted ideas for projects on a few dispersed pages:
1) 'brainstorm' on potential topics in [GoogleDoc](https://docs.google.com/document/d/1dIyqc_vnjM2LXwDOuPZACv4o1mR27DaLyCJkj7SQvxg)
2) matrix with ["Applikationsvorschläge und Datenbedarf"](https://github.com/BaselHack/verein/files/1242033/Daten.data.driven.challanges.pdf)
3) [exchange on github](https://github.com/BaselHack/verein/issues/42) on data provider
4) additional personal communications with candidate participants

=> derive from this overview a brief description of 1-3 most appealing ideas

**Comment by schmidchr** [comment]
-> the doodle converged to Mon Sep-25 at 16h
@StanBarrows : thanks for offering to organize a room at FHNW Basel - Peter-Merian (location close to Basel SBB?) => could you confirm precise directions and room number (both here and in doodle)

**Comment by StanBarrows** [comment]
Good morning everyone, I reserved classrom 1.02 @ FHNW, Peter Merian-Strasse 86, 4052 Basel from 15:30 until 18:30. The room information will also be displayed on the info-screen at the building entrance. See you later

**Comment by andgart** [comment]
Sabine Schneeberger wird auch kommen (#42 )

**Comment by schmidchr** [comment]
potential templates for topics/projects:
- "Speed-control-here": app to suggest locations of speed controls based on history of past radar measurements [Police dep BS], geolocation, fraction of speeding, incorporate feedback by inhabitants
- "nearest-free-BS-parking-space": complementing GPS navigation-app, include public parking houses [live RRS-feed, occupation history], parking fee, occupation sensors "Blaue Zone", ...
- "My-Watering": predict required plant watering from data of sensors for humidity [], weather forecast, ...

-> YOUR ideas: ...

**Comment by andgart** [comment]
meeting 02.10.2017 feedback: only take 1 and present this nice:

"nearest-free-BS-parking-space": complementing GPS navigation-app, include public parking houses [live RRS-feed, occupation history], parking fee, occupation sensors "Blaue Zone", ...

**Comment by schmidchr** [comment]
@culmat @JJatsch : there is a project proposal for an implementation of blockchains for applications in SME (owner registry, documentation in logistics, ...). We noticed an involvement of Baloise in the upcoming [blockchaincompetition.ch]( https://www.blockchaincompetition.ch) in November in Zug. <br> => Do you know of participants, or members of the BaselHack team with corresponding skills, that could be interested in further developing such a project/topic towards a pitch?

**Comment by schmidchr** [comment]
@andgart @culmat : put online a teaser  description:
https://github.com/BaselHack/BaselHack2017/wiki/Topics
-> feel free to modify / improve; I am personally very rarely concerned with car parking in BS :)

**Comment by teddybeaker** [comment]
great, thanks @schmidchr
