### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#5]
open channel
invite people

-> Andres

**Comment by culmat** [comment]
wären [mentions](https://github.com/BaselHack/verein/issues/13#issuecomment-312689513) nicht eine Lösung?
Dann hätten wir alle info an einer Stelle und nur eine [Liste der Mitglieder](https://github.com/orgs/BaselHack/teams/mitglieder/members) zu verwalten?

**Comment by andgart** [comment]
@teddybeaker @culmat: Ich habe mal einen slack channel aufgemacht (https://baselhack.slack.com), aber noch keine Einladungen versendet

**Comment by teddybeaker** [comment]
@andgart: ich frage bei der nächsten Sitzung nach, ob uns Slack hilft oder behindert in der Vorbereitungsphase.

**Comment by teddybeaker** [comment]
@andgart: habe nachgefragt und der Tenor ist, dass uns Slack hilft, sofern wir allfällige Entscheidungen immer noch auf Github festhalten. Also bitte alle von https://github.com/BaselHack/verein/wiki/Team einladen wenn du zurück bist, merci

**Comment by andgart** [comment]
Done
