### ISSUE TITLE
Awards

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#52]
- what will the prizes be
- who will get a price? do we have categories?

**Comment by mayvi** [comment]
Thomas Berger has confirmed that Basel-Stadt (ZID) will contribute CHF 300 as Pro Innerstadt vouchers as Award for the winning Team.

**Comment by schmidchr** [comment]
thank you to @mayvi !
request for other opinions: in my view, a monetary price for the winning team is expected to be rather symbolic, yet CHF 300 divided by ~8 member (eg. for a team dinner) might not allow for a too generous meal, ie the winners might be required to complement?
Any options to top-up from our general budget, eg double the sum?

**Comment by schmidchr** [comment]
@hauckch1 : you offered to produce customized buttons #57 
How about a button "I am a proud finisher of the BaselHack2017" or similar, inspired by marathon sports events?

**Comment by hauckch1** [comment]
@schmid - we can do (design, create) that also on short notice - just has to fit to the small size.

**Comment by teddybeaker** [comment]
@mayvi : could you organize another 200CHF in Pro-Innenstadt-Gutscheinen that BaselHack will pay for? We discussed this yesterday after you where gone.

**Comment by teddybeaker** [comment]
participants from the first three teams were given
- a certificate each
- a book from FHNW each
teams were given
- a bronze/silver/golden keyboard
the winning team got pro-innenstadt Gutscheine

Tip for next time:
- prepare certificates with names on Sunday, just put in the rank in the end.
