### ISSUE TITLE
Feedback Questionnaire - after the Hackathon

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#55]
# Questions for participants (-> survey):
- how did you hear about baselhack?
- what were your expectations? 
- were your expectations met?
- what went well?
- where/what can we improve?
- what did you learn?
- what was the biggest challenge for you?
- was there anything unique about the Baselhack (in case you participated in other ones before)?

- how did you like the location?
- what do you think about the size?  ____ what size do you mean?___

- did you come alone or with a team?
- did you stay the whole two days?

- I'd like to receive job offers from the sponsors of BaselHack. 
(If you answer "yes", you agree that we will give your e-mail address to our sponsors so they can contact you with job offers)
- would you participate again?
- would you pay if it weren't for free?
- how much would you pay if it weren't for free?

## Follow-up tasks
- remove last question to keep data anonymous
- analyse/cluster responses
   - share outcome with events@baselarea.swiss 
- send e-mail addresses of participants, that would like to receive job offers (last question) to sponsors

# Questions for sponsors (-> ask them at road show):
- what were your expectations? 
- were your expectations met?
- did you attend the hackathon?
- what went well?
- how can we improve next year?

# Questions for organisators (-> retro https://github.com/BaselHack/verein/issues/66):
- what went well?
- what went wrong?

**Comment by teddybeaker** [comment]
Hi @jjerlich, thanks for adding questions. I built the form (https://baselhack.typeform.com/to/OD48ne), had to cram in the questions a bit because the free typeform only allows for 10 questions (and the payed version costs 25€ per month but has to be bought for 1 year -> 300€). Feel free to edit.

**Comment by teddybeaker** [comment]
Sent to all registered participants on October 31st.

Subject: BaselHack 2017: feedback and further support

Dear BaselHack-participants

The first BaselHack is over. We had a great time and I hope you did too. To know what worked well and what we can improve in the future, we'd like to get your **feedback**: https://baselhack.typeform.com/to/OD48ne

**Possible support for further development of projects**

**Smart Regio Basel** invites you to present your ideas and prototypes on www.smartregiobasel.ch. They also offer **help** when realising further smart solutions for Basel.

**Canton Basel-Stadt** is looking for applications using #opendataBS. Teams who worked with their data - or generally people interested in #opendataBS - are invited to attend the "Open Stammtisch" https://twitter.com/_sabin_/status/921339516157353984
In the context of the **OGD pilot project 2017/18**, the Canton Basel-Stadt is supporting and promoting sample applications. They would also like to know more about the needs of their users such as if raw or prepared data should be provided, if the data should be provided via APIs etc. Contact https://twitter.com/_sabin_ if you have questions or input.

**Handelskammer beider Basel** (Chamber of Trade) does have a **support programme**. You can still apply until mid-November for support, check out http://www.are-you-digital.ch/de/Die-Initative/Digital-Talent.php for details.

**FHNW** has a **support programme** to get innovative ideas fit and ready for the market by providing coaching, workshops etc. Find out more on http://www.sechallenge.ch/innovation/bewerben/

We ​did clone the state of your projects as it was on Sunday afternoon. I
​f you further develop your project, we can add a notice to our fork directing people to your original repository if you want. Just let us know (info@baselhack.ch).

That's it for the BaselHack 2017, we hope to see you again next year.

Your BaselHack Team

--

email: ​info​@baselhack.ch

website: https://baselhack.ch

address: BaselHack, c/o BaselArea Swiss, Dufourstr. 11, 4010 Basel

**Comment by teddybeaker** [comment]
If we want to look at the participant feedback at our retro (https://github.com/BaselHack/verein/issues/66) as well, someone other than me has to extract the responses. Account data is at the usual place.

**Comment by JJatsch** [comment]
I can do extraction and analysis of responses.
