### ISSUE TITLE
contact participants and collect additional information

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#56]
Dear BaselHack-participants

Thanks for your registration - it's great to have you on board of the first BaselHack ever.

In order to run the actual event as smooth as possible we have a few questions and important announcements for you.

We want to get to know our folks a little bit better. So please complete this form as soon as possible: https://baselhack.typeform.com/to/BCJ5ah

We are giving you the chance to get to know your potential team mates, build your team, meet the organizational committee and get answers to all your questions before the actual BaselHack. Come and join us for the Pre-Event on Friday, 20th October. For a better estimate of how much food and drinks is needed, please register [here](https://www.baselarea.swiss/baselarea-swiss/channels/innovation-events/2017/10/baselhack-pre-event.html) for the pre-event (note that this is not the registration for the BaselHack).

We stronlgy advise to use github during the BaselHack. If you do not have an account yet, you might considering setting it up beforehand and join the BaselHack github repository? https://github.com/BaselHack/BaselHack2017

In order to get access to the internet you will need to bring your mobile phone

All attendees of BaselHack must agree and respect the "BaselHack Community Code of Conduct" of being open, considerate and respectful. Please find the details here: https://github.com/BaselHack/verein/wiki/Code-of-Conduct-(Verhaltenskodex)

You will find all additional organizational information (e.g. how to get there and what to bring) here soon: https://github.com/BaselHack/BaselHack2017/wiki/Infos-for-Participants

We are looking forward to seeing you at the Pre-Event and at the BaselHack itsself. Let's get innovative.

The BaselHack Team

--

email: event@baselhack.ch

website: https://baselhack.ch

address: BaselHack, c/o BaselArea Swiss, Dufourstr. 11, 4010 Basel

**Comment by teddybeaker** [comment]
Mail sent on October 5th to 83 participants from event@baselhack.ch

**Comment by teddybeaker** [comment]
Resent mail on October 10th to the same 83 participants from stefani.gerber@bluesky-it.ch

_**Disclaimer**: we already sent this e-mail last week but got the feedback that it did end up in quite a few spam folders. Therefore, we resend it from a different address and hope to reach all of you this way. We apologize for the inconvenience._

**Comment by teddybeaker** [comment]
@mabrimo I'll track when I sent what to whom and when i merge the typeform-answers into the excel here

**Comment by teddybeaker** [comment]
sent out 9 mails on October 11th and 8 on October 13th.

**Comment by schmidchr** [comment]
On 2017-10-16 19:23, teddybeaker wrote:
"@schmidchr: I talked about the "My idea for the BaselHack (Optional)" column. If you can follow up on some of the promising entries there that would be great."<br>
-> thanks for the Excel table, I will sent a message to the (few!) participants with an entry in column 10, to point them for a preliminary teaser description to be entered to:
https://github.com/BaselHack/BaselHack2017/wiki/Topics
or alternatively for those with clearer ideas to a template repository for developing a pitch presentation:
https://github.com/BaselHack/-00_TEMPLATE-PROJECT 
=> depending on the outcome, we might recontact all registered to incite more pitch presentations?

**Comment by schmidchr** [comment]
@hauckch1 
I think you proposed to generate a word cloud from the keywords submitted by the registered. Attached a raw extract of the column with the skills:
[skills-word_Cloud.txt](https://github.com/BaselHack/verein/files/1390671/skills-word_Cloud.txt)
-> could you give a shot to create a corresponding graphic? thanks!

**Comment by teddybeaker** [comment]
sent out the following reminder to 83 participants (those registered before October 13th)

Dear BaselHack-participants

Our Pre-Event will take place this friday, October 20th. It is an opportunity to meet other participants beforehand and talk about topics for the BaselHack. If you'd like to participate, register here: https://www.baselarea.swiss/baselarea-swiss/channels/innovation-events/2017/10/baselhack-pre-event.html

Also, if you haven't already done so, please answer some questions to help us plan the event better: https://baselhack.typeform.com/to/BCJ5ah

See you soon,

Your BaselHack Team

--

email: event@baselhack.ch

website: https://baselhack.ch

address: BaselHack, c/o BaselArea Swiss, Dufourstr. 11, 4010 Basel

**Comment by teddybeaker** [comment]
sent out 2 mails to newly registered participants on the 17th.

**Comment by schmidchr** [comment]
@teddybeaker : how do you handle 'participants' with specific roles (Orgateam, jury, coaches, sponsors, ..), do you require lists of these, in which format? 
-> For batch printing, food, seating, general info, ... it may be easier to have them included in a general participant list, yet I noticed there are still overlaps that we formally excluded (registered participant AND jury, ..)

**Comment by teddybeaker** [comment]
@mabrimo: does the event-team have any preferences for handling these cases?

**Comment by schmidchr** [comment]
sent two mails from jury-admin@baselhack.ch:
1) invitation to eight participants (in BCC) having submitted an idea with their registration -> encourage to further develop to pitch presentation
2) similar invitation to submitter of [blockchain project](https://github.com/BaselHack/BaselHack2017/wiki/Topics) to further develop to pitch presentation

**Comment by hauckch1** [comment]
While working on the wordcloud.

@teddybeaker @schmidchr 

I discovered this content, which I interpret not as available expertise and background, but it could be a pitch?

"Application for iphone/android to timeline baby development milestones (photos and videos). Personalize the photos and videos by adding an icon of the specific milestone card (32 different milestone cards). Create a priceless video memory showing all the different baby milestones (photos and short video) that you and your child will treasure forever. You will have access to the same account to contribute with photos/videos the baby timeline. Share the individual photos/videos or compiled video memory privately or in social media. "

**Comment by hauckch1** [comment]
non-"Wordcloud" results, but simple list

**approach:** 
I tried to use Openrefine, does not make sense. 
Went to manual process: copy to Excel, normalize manually with copy/paste and retyping, sort alphabetically, count.
Thus it is some "manual" clustering, but no real semantics behind, no categorization. I did not try to put related items into single buckets, therefore, there were many single items, relatively few multiplicates.

And therefore a workcloud does not make so much sense. Instead, simple lists provide more info.

**Results:**

**Most frequent items:**
Java (13)
Python (12)
Javascript (9)
C++ (5)
Machine learning (4)
PHP (4)

**3 times:**
CSS
Data analysis
Frontend
HTML

**2 times:**
Angular
Arduino
Backend
Creativity 
Experience
Haskell
Innovation
Linux
Motivator
Project Management
R
Rasberry Pi
SQL
Team Lead
Web Apps

**Unique:**
analytical mindset
Apache Spark
APIs
Artificial Intelligence
AWS
Bioinformatics
Biology
Bluetooth
Business Analysis
Business Idea
Business Modeling
Business Process Modelling
C
C#
Cloud provisioning
coding
communicate
D3
Data/System Architect
Deep learning
DevOps
Distributed Architectures
Distributed computing
Doctrine
Electronics
EnOcean Radio Technology
ESP8266
FP
Freifunk
GNU/Linux
Go
Hacking
Hadoop
Hive
Humor
Idea Generator
Idea simplification
Ideation
Implementing designs in SCSS
Industry knowledge
Innovation Management
Innovative Business Models
jQuery
keep good atmosphere
Matlab
Maven
Networking
Numpy
OO
Open Source
openminded
Optimization
OTT
peer-to-peer
Platform design
PredictionIO
Problem solving
Process Design
Product Management
push people to limits
regex
Requirements engineering
SAS
Security
Software architecture
Software engineering
Strategy
Swarm robotics
Symfony
Sysadmin
technology
touch of inspiration
Tschunk cocktail
TypeScript
UI Development
Vaadin
video streaming
Vision Development
Vue.js

**Comment by schmidchr** [comment]
@hauckch1 : thank for highlighting this description, where did you discovered this?
If I remember correctly, a very similar description was included in the table with the registration info, and the submitter is included in the recipients of my message of Oct-19th encouraging to prepare a pitch presentation.

**Comment by schmidchr** [comment]
@hauckch1 : thank you for creating the frequency table. I imagined to create a simple wordcloud, without any semantics, clustering, ... It is obvious that the data set is relatively small (by far not all registrations included keywords ...), with a large number of unique occurrences, typos ... <br>
Yet I reasoned that the few high frequent terms (java, ...) could visually display a (minor) focus in the very diverse skills (13x out of ~100 participants). Feel free to post a link to a corresponding graphics, then we can decide if we want to use it ie in the introduction address or on BaselHack.ch?

**Comment by hauckch1** [comment]
I used https://www.jasondavies.com/wordcloud/ to create something (attached), will also print it and bring with me later today.
![baselhack_wordcloud](https://user-images.githubusercontent.com/8237033/31822720-fca1bb9e-b5a9-11e7-9bca-3ca563c2a189.gif)

**Comment by teddybeaker** [comment]
very cool! I also added it to the slides for today

**Comment by schmidchr** [comment]
Perfect, exactly what I had in mind :)
FYI, unfortunately I can not join tonight, have fun!

**Comment by teddybeaker** [comment]
@schmidchr: I added jury and coaching members to our general participant document, but on separate tabs. @lisaandrea will start printing the name tags soon.

**Comment by teddybeaker** [comment]
sent out the following reminder to 95 participants

Dear BaselHack-participants

Only four nights' sleep and the BaselHack will begin!

We're still busy getting the last details ready. We'll add additional information to  https://github.com/BaselHack/BaselHack2017/wiki/Infos-for-Participants as we go. So please check it for updates now and then.

One important detail regarding the **pitches**:
- If you already have an idea, you **_can_** put it up on https://github.com/BaselHack/BaselHack2017/wiki/Topics (direct text or link to your own public github project site) beforehand to let other participants know what you have in mind. But you don't have to.
- We'll register the pitches on **_Saturday morning_** as they are held. So it's perfectly fine if you just show up then and hold your pitch, without registering it anywhere beforehand. If you intend to use audiovisual support, don't forget a connector from your device to HDMI.
- We ​also ​
have listed some data sources for you on https://github.com/BaselHack/BaselHack2017/wiki/Topics, in case you need an inspiration.

We do have a slack channel, if you'd like to sign up please use the following link:
https://join.slack.com/t/baselhack/shared_invite/enQtMjU4Nzc1ODA4MjQwLTgzNDhlZmYxZWJiNTA2NWY2ZjY1MDkwNDYwMzhlZjBiN2RjMmEzODkwOWQ3YmM5NTI5ZDYwNTcwNGY4OWQ4YjY

See you soon,

Your BaselHack Team

--

email: event@baselhack.ch

website: https://baselhack.ch

address: BaselHack, c/o BaselArea Swiss, Dufourstr. 11, 4010 Basel
