### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by hauckch1** [BaselHack/Verein#57]
Create buttons:

print on paper:
- I use 2 different styles, trying to stay on brand:
- - with the Baselhack 217 logo, color 14FFF2
- - with the Baselhack logo, I deleted the "2017", color FFFD00 (yellow)
we might possibly use the yellow ones for the baselhack orga people

press the buttons:
not yet done. Will make a first set of 12 pins and 12 magnets, bring to a meeting.

**Comment by hauckch1** [comment]
The buttons that I can make are too small, 2 cm useable diameter only, too much text will not be readable.
I'll bring some to the pre-event later today.

sidenote: had to make the bluegreen color lighter, color calibration is not easy, background was too dark, text was hard to read.

**Comment by schmidchr** [comment]
OK for the small size, so possibly for a button 'rewarding' those contributing to the final presentations, we could use a text "Achiever" &  Baselhack 2017 logo

**Comment by hauckch1** [comment]
I can bring the machine to the event and then we "hack" it on site ;-)
