### ISSUE TITLE
cheat-sheet for staff

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#60]
- emergency numbers (FHNW etc.)
- times
- phone list
- Einsatzplan
- explanations (e.g. vests)

**Comment by schmidchr** [comment]
FYI, quite extensive general guide for hackathons:<br>
https://hackathon.guide/
=> to me it seems like we are mostly on track, possibly this guide hints for a few points overlooked so far? infrastructures @mabrimo

**Comment by teddybeaker** [comment]
started on https://github.com/BaselHack/verein/wiki/Infos-for-Staff
