### ISSUE TITLE
template for repository

### ISSUE THREAD

**Issue by schmidchr** [BaselHack/Verein#61]
generated a template for the repositories the participants should open: 
https://github.com/BaselHack
-> please let me know if the descriptions are clear both for github starters and for experienced users of git on the commandline? Feel free to improve by directly modify the template.

**Comment by schmidchr** [comment]
@StanBarrows : could you verify the available connection type(s) of the audiovisual equipment (HDMI, VGA, ..) for the presentations, if on the premises for checking the plugs for the power lines? Thanks

**Comment by StanBarrows** [comment]
@schmidchr sure! Will be there on Thursday.

**Comment by hauckch1** [comment]
a coach for git / github would be nice https://github.com/BaselHack/BaselHack2017/wiki/Coaching

**Comment by schmidchr** [comment]
@hauckch1 some coaches agreed in recent exchanges to coach also on less spectacular 'basic' skills like usage of Github. I will ask all of them to list this also on the coach wiki page

**Comment by schmidchr** [comment]
@arinnjay I simplified the template repository and its description, including a mini-tutorial. Feel free to test and comment :)
