### ISSUE TITLE
slack channel for coaches

### ISSUE THREAD

**Issue by schmidchr** [BaselHack/Verein#62]
I have created a #coaches channel on our slack site with the intention to propose this to the participants as an initial contact to coaches. For this we will need to ask the participants and coaches to join the slack team.
Two questions:
1) does anybody of you know how to find/generate a URL, with which interested participants and coaches can join our Slack team site?
2) Do we need to mask/delete our 'team-internal' channels; as far as I know we rarely used the system? [Slack seems more advantageous for larger groups and immediate exchanges]

**Comment by andgart** [comment]
1. see https://get.slack.help/hc/en-us/articles/212675257-Join-a-Slack-workspace for different ways to get invited -> depending on strategy how to use slack during the hack
2. imho to complicated and not needed

**Comment by teddybeaker** [comment]
2. 👍 , I checked what we have in the general channel and I don't mind if anyone reads that

**Comment by schmidchr** [comment]
that was quick, so I assume we can invite on opt-in basis (to be tested!)


-------- Forwarded Message --------
Subject: 	Re: URL for joining workspace
Date: 	Fri, 20 Oct 2017 08:20:16 +0000
From: 	Nicholas Deary (Slack) <feedback@slack.zendesk.com>
Reply-To: 	Slack <feedback+id1517983@slack.zendesk.com>


\# Please type your reply above this line \#
On Oct 20, 1:20 AM PDT, Nicholas Deary (Slack) wrote:

Hi Christoph,

We do have a feature very similar to that! You can generate shared invite links to send out to participants. When they click this link, they will be able to create an account on the workspace themselves.

http://my.slack.com/admin/shared_invites

These invites are good for up to 1000 users and for 30 days. You can also generate subsequent links once they expire.

Please let me know if you need anything else!

Best wishes,
Nick

on Oct 20, 12:51 AM PDT, Christoph wrote:

Dear Slack helpdesk,
I am part of the organizing team of BaselHack 2017. We consider proposing Slack to our participants on an opt-in basis, ie we do not have a complete participant list to generate invitation mails.

At previous events I observed URLs in the format
http://tedxbasel.us10.list-manage1.com/track/click?u=13d9a72ee03254079a6a1&id=e2009e57&e=07f5b3dc
enabling precisely this.
Could you provide us with such an URL for our workspace baselhack.slack.com

Thank you very much for your assistance,
Christoph

**Comment by schmidchr** [comment]
Invite link for baselhack workspace
https://join.slack.com/t/baselhack/shared_invite/enQtMjU4Nzc1ODA4MjQwLTgzNDhlZmYxZWJiNTA2NWY2ZjY1MDkwNDYwMzhlZjBiN2RjMmEzODkwOWQ3YmM5NTI5ZDYwNTcwNGY4OWQ4YjY

FYI: For security, invite links will expire and can be used by up to 1000 people. If you need to, you can get a new link.
