### ISSUE TITLE
cut video material

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#65]
@hauckch1: I assigned this to you because you said you might know someone (not because you'll have to do it :) )
@jjerlich: if I remember correctly you suggested to work on the screenplay

**Comment by hauckch1** [comment]
approaches: 
- I contacted her, no reply yet
- we could start there, on-site, locally (simple cuts and edits).

**Comment by schmidchr** [comment]
I do know Christian Heuss (former head science coverage at SRF). He runs in part-time an independent communication office (website not really informative: https://www.smartscience.ch/).
If we clearly define the collected materials (footage, pictures, ....) and our aims and expectations, time lines, ..., I can contact him asking for a quote?

**Comment by hauckch1** [comment]
my colleague Georgina came by to the end of the Hackaton, I introduced her to @jjerlich , and we discussed several options.

I don't think that we are in a position to really clearly define the specifications well enough for a solid quote.

**Comment by hauckch1** [comment]
The videos are on my private server:
http://freepeer.synology.me/~freepeer03/

I cut them into separate video files, and reduced the resolution (and thereby file size, still good enough):
the 1-minute pitches
the 5-minute presentations
the 6-minute award finale

The full high-quality files are also hosted there, but not linked.

Please check if it works for you - I'm using the html5 video tag, which is still supported differently on different platforms, and I am grateful about bug reports.
Don't complain about the very basic style - I consider this simplistic retro design as "feature not bug" ;-)

@arinnjay - what about the pictures?

**Comment by culmat** [comment]
Can you post them on https://www.youtube.com/channel/UCat5BvUrfV7am60pLpuy8oQ   ?
If not can you sent me the links to the high quality videos, so I can upload them to youtube?

**Comment by schmidchr** [comment]
@hauckch1 
What I meant with "our expectations on the processed video material": in my limited experience with PR specialists, I learned that they always want to know "which general message to which target public"? 
-> successful first edition of BaselHack, fun and 'agile' coming together of specialists from different domains, as unique advantage of a hackathon format, 
-> information for our present and future participants, sponsors of the event and of potential further developments of hacks, ...

**Comment by hauckch1** [comment]
@culmat - 

preferred option: can I upload to the channel as well? how?
alternative: file structure goes like this (right mouse click, save locally):
http://freepeer.synology.me/~freepeer03/data/20171028_29/baselhack2017_01_pi.m4v
http://freepeer.synology.me/~freepeer03/data/20171028_29/baselhack2017_01_pr.m4v
http://freepeer.synology.me/~freepeer03/data/20171028_29/baselhack2017_02_pi.m4v
http://freepeer.synology.me/~freepeer03/data/20171028_29/baselhack2017_02_pr.m4v
and so on
and at the end:
http://freepeer.synology.me/~freepeer03/data/20171028_29/baselhack2017_finale.m4v

whereby:
 pi = pitch, pr = presentation
_01_ = team number, valid values: _01_ to _14, but without _08_ _09_ _10_
team names / project names:
01 Next Beer App
02 Blink - Social Connect Mobility
03 Illuminar - Light Hands Free
04 Smart Contacts
05 Visual Fish
06 PubTransViz
07 Basel Inside
11 Clockchain
12 Traffic Squad
13 Whitch Way
14 My Side Effect
Finale:  3rd: My Side Effect, 2nd: Smart Contacts, 1st: Clockchain

**Comment by hauckch1** [comment]
@schmidchr - indeed, and: that's probably very much our task, to come to grips what we want and how, in general? that what I meant by "specifications".

**Comment by schmidchr** [comment]
OK, I guess there are better chat systems than the commenting in github :)
-> so we are on the same page, and "specifications" of technical nature (length, resolution, ...) can be derived from the message and the channel.

**Comment by schmidchr** [comment]
Just in case the feedback is still required, I was able to view the videos on the synology with reasonable quality. I agree with the suggestion to (also) use youtube, in my understanding the current version of 
https://github.com/BaselHack/BaselHack2017/wiki/Reporting
allows only users of facebook and/or twitter to visualize the videos?
Nevertheless a good start, thanks to @jjerlich and @hauckch1

**Comment by hauckch1** [comment]
the Synology NAS is just my pet project. Agreed to put them on Youtube, I can do it if I have account and password, else someone else can grab from Synology (links above) and do it.
My NAS is accessible for everyone - if I have it switched on ;-) And of course, if one knows the links. Youtube is better for sharing, and for persistence.

**Comment by culmat** [comment]
@hauckch1 have added you to our Google Brand Account. You should now be able to upload videos to the youtube channel?
https://www.youtube.com/channel/UCat5BvUrfV7am60pLpuy8oQ  
https://aboutme.google.com/b/102925923083524310072/
https://myaccount.google.com/brandaccounts/102925923083524310072/view

**Comment by hauckch1** [comment]
yes, will do, in the evening.
Cheers
/chris

On Tue, Oct 31, 2017 at 1:24 PM, Matthias Cullmann <notifications@github.com

**Comment by schmidchr** [comment]
@StanBarrows  is there any footage available from the GoPro recordings?
            potential highlights:
                Sa morning: the 'spontaneous' lineup of the pitch presenters
                Sa evening: the movement induced by the 'pizza is ready' announcement

**Comment by schmidchr** [comment]
Question on options to archive the full high-quality files on a location with shared access? 
What is the total volume of all these files, what are the limits of our accounts (github, google drive, ...)?

**Comment by jjerlich** [comment]
Group descriptions to be found on https://github.com/BaselHack/BaselHack2017/wiki/Reporting

**Comment by hauckch1** [comment]
Our Youtube channel: https://www.youtube.com/channel/UCat5BvUrfV7am60pLpuy8oQ
Playlist BaselHack2017 pitches https://www.youtube.com/watch?v=xf7pr76mSH4&list=PLiQSCdfYuZ8b62bADeyyAD7IQqYZUqgrx
Playlist BaselHack2017 presentations https://www.youtube.com/watch?v=IlrkizWK9Ks&list=PLiQSCdfYuZ8bWPfWyo2PBGpN5NJLMphBH

There are still things that might be improved, but I am not sure:
- add the team/project name into the title, not only the code, so it is more speaking?
- add the specific text per project , from here https://github.com/BaselHack/BaselHack2017/wiki/Reporting?
- add a short summary of the whole event to each video?
- a descriptive text for the whole Youtube channel

**Comment by schmidchr** [comment]
@jjerlich : not sure if the notification of modifications of 'your' wiki page works reliably?
So for your info, I added 'external' media coverage of BaselHack to
 https://github.com/BaselHack/BaselHack2017/wiki/Reporting
Please feel free to further modify and let me know if this corresponds not to your ideas :)
