### ISSUE TITLE
RoadShows for Sponsors

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#68]
Basler, Adobe, Bluesky, FHNW, Actemium, BaselArea Swiss, Smart Regio Basel and Standortförderung Baselland do have road shows in their package.

- contact, thank for their support and ask if they'd like to have the road show
- setup a date
- prepare content
- do road show

**Comment by culmat** [comment]
Baloise could be 09.11. We have an unconference day on that date. This is a perfect platform.
