### ISSUE TITLE
Setup way for sending newsletter

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#69]
- evaluate a tool
- configure it (make sure people can unsubscribe!)
- test it with team members (make sure our e-mails don't end up in spam filters)
- initial import:
  - participants from the hackathon
  - people registered to stay updated (https://baselhack.typeform.com/to/GqbMkw)

**Comment by jjerlich** [comment]
@StanBarrows will choose mailchimp, otherwise please advice of which tool to use, goal better integration with all other digital tools in use, thanks

**Comment by StanBarrows** [comment]
@jjerlich I'm happy with Mailchimp =)!

**Comment by StanBarrows** [comment]
Mailchimp wurde eingerichte, Zugangsdaten sind auf GoogleDocs
