### ISSUE TITLE
Mitgliederversammlung

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#71]
# Vorgängig versenden
- Protokoll der letzten Versammlung
- Jahresbericht des Vorstandes
- Jahresrechnung und Budget

# Traktanden
- Abschaffung Mitgliederbeitrag
- Mutationen Vorstand

**Comment by teddybeaker** [comment]
@culmat: "Jahresrechnung und Budget" haben wir hier auch noch als "vorgängig zu versenden" drin. Kannst du das noch machen, sobald du aus den Ferien zurück bist?

**Comment by culmat** [comment]
Habe die Dokumente unter https://github.com/BaselHack/verein/wiki/Mitgliederversammlung verlinkt

**Comment by teddybeaker** [comment]
merci @culmat. Habe auf GoogleDrive die Ordnerfreigabe wieder eingeschränkt (war alles offen für alle).
