### ISSUE TITLE
Contact last years sponsors

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#86]

**Comment by JJatsch** [comment]
Bis auf Adobe und Bluesky alle letztjährigen Partner und Sponsoren kontaktiert.

**Comment by JJatsch** [comment]
@teddybeaker Hi Steffi, könntest du bei euch anfragen ob bluesky wieder sponsert?
Haben wir eine Mailadresse von Goran?

**Comment by culmat** [comment]
Baloise wird wieder Sponsor
UniBasel als Partner?

**Comment by culmat** [comment]
https://docs.google.com/spreadsheets/d/1pcEedLpQcOH3sZUQ0q9FULL_vKDzfxODBKWBo_LUn84/edit#gid=0

**Comment by teddybeaker** [comment]
@JJatsch: @dariotodaro wird das bei Bluesky koordinieren/anfragen. Kannst du ihm noch Bescheid geben, was für Bedingungen/Packages angedacht sind? Merci
