### ISSUE TITLE
Find new sponsors

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#87]
... this applies to everyone

**Comment by StanBarrows** [comment]
BLKB

**Comment by StanBarrows** [comment]
Digitec (Markthalle)

**Comment by sjoerd222888** [comment]
I would like to learn about sponsoring opportunities. What sponsoring packages do you have? Neither website nor this repo provides a lot of information.

You should make sponsoring information available on the website. Even if it is only something like: "If you want to learn about sponsoring opportunities please send an email to sponsoring@baselhack.ch". On the currently defunct page 'Sponsors'? Or a new page 'Become a Sponsor'?
