### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#89]
- define content
- pimp the website
- sync or link w/ social media
- implement dynamic sections / areas
- english only tbd

**Comment by culmat** [comment]
Hi, I made a proposition for a more modern look: http://test.baselhack.ch/mod/
What do you think?
You can download and play with it here http://test.baselhack.ch/mod.zip

**Comment by StanBarrows** [comment]
That's looking great! I'll try to implement this =)

**Comment by culmat** [comment]
einzelne tasks sieher https://github.com/BaselHack/baselhack.ch/issues
