### ISSUE TITLE
Write recommendations for data delivery

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#9]
points like
- public data
- easy accessable format
- availablity at event

-> Martin, Andres, Vivienne

**Comment by sabinsc** [comment]
Perhaps Data Publishers could pitch their OpenData in a Pre-Event. BaselHackers could then prepare their BaselHack-Project. Not only programmers should be involved, but also designers all together with their entourage of in the matter interested people - interdisciplinary teams that develop something together. Perhaps we could also gain school projects to participate.

**Comment by jjerlich** [comment]
24.7.2017 Meeting with @sabinsc and Andres Gartmann about available data and its format. Results will be discussed in Vereinsmeeting on 27.7.2017

**Comment by jjerlich** [comment]
Offer for a pre-workshop about data from School of data www.schoolofdata.ch / forum.schoolofdata.ch  made by Oleg Zaworsky
Olge owns www.datalets.ch/dribdat - a "Swiss made" open source hackathon helper - which can be used to put all the ideas/challenges/teams/projects together in one place, and optionally connected to a forum or Slack for online collaboration. See hack.opendata.ch and now.makezurich.ch for examples

**Comment by teddybeaker** [comment]
Won't collect data beforehand, everybody brings their own data
