### ISSUE TITLE
Redefine on-boarding process

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#91]
- ticketFrog (ask owner if she wants to join)
- ti.to
- alf.io
- eventbright
- xing

**Comment by mayvi** [comment]
Was passiert, wenn ich mich als Teilnehmer angemeldet habe:
- Prozess von der Anmeldung bis zum Hackathon

**Comment by culmat** [comment]
Lösung in baselhack.ch implementiert
