### ISSUE TITLE
Inform PR classics

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#93]
- Prepare material and spread to:
- TV
- News papers
- Radio

**Comment by StanBarrows** [comment]
Adobe?, Firmen in Basel, Kalender Einträge?

**Comment by jjerlich** [comment]
Communication via Baloise Jobs Blog - Jonas und Jutta
traditional PR through them

**Comment by culmat** [comment]
Hat hier nichts zu suchen, aber zur Info : http://techup.ch/2671/baselhack
