### ISSUE TITLE
Check if location is available

### ISSUE THREAD

**Issue by michelpfirter** [BaselHack/Verein#95]
- 17 / 18 November 2018
- whats the max capacity of the location -> gives aimed hackers

**Comment by mabrimo** [comment]
E-Mail sent to Francoise Payot of HGK if we can have the location again and if it is available on the specific date

--> Event-Team from HGK will decide on it upcoming Monday 26th Feb

**Comment by mabrimo** [comment]
Good News: We can have the location again
BUT: LOCATION IS NOT AVAILABLE ON THE SPECIFIC DATE 17/18 Nov

--> What about last November weekend (24/25 Nov) or first December weekend (1/2 Dec)

**Comment by StanBarrows** [comment]
FHNW provisorisch Reservieren am 24/25 November. Zusätzlich Markthalle noch abklären (jeweils an beiden Weekends 17/18 & 24/25)

**Comment by culmat** [comment]
Der BaselHack 2018 findet am 24 / 25 November an der FHNW Dreispitz statt.
